### ISSUE TITLE
1.4.2_가비지 컬렉터의 작동 방식과 메모리 수거 대상의 기준에 대해 설명해주세요.

### ISSUE THREAD

**Issue by Stilllee** [Coding-Village-Protector/core-js#1]
📝 14p
❓ 가비지 컬렉터의 작동 방식과 메모리 수거 대상이 되는 기준에 대해 설명해주세요.

**Comment by eeeyooon** [comment]
가비지컬렉터는 런타임 환경에 따라 특정 시점이나 메모리 사용량이 포화 상태에 임박할 때마다 자동으로 수거 대상들을 수거합니다. 어떤 데이터에 대해 자신의 주소를 참조하는 변수의 개수를 참조 카운트라고 하는데, 이때 참조 카운트가 0인 메모리 주소는 가비지 컬렉터의 수거 대상이 됩니다. 수거된 메모리는 다시 새로운 값을 할당할 수 있는 빈 공간이 됩니다.

**Comment by lulla-by** [comment]
가비지 컬렉터의 메모리 수거 대상은 참조 카운트가 0인 메모리 주소입니다.  참조 카운트는 어떤 데이터에 대해 자신의 주소를 참조하는 변수의 개수를 뜻합니다. 즉 자신의 주소를 더 이상 참조하는 변수가 없을 때 참조 카운트는 0이 되며 가비지 컬렉터는 런타임 환경에 따라 특정 시점이나 메모리 사용량이 포화 상태에 임박할 때 자동으로 이러한 수거 대상들을 수거합니다.

**Comment by chaehaeun** [comment]
가비지컬렉터는 런타임 환경에 따라 **특정시점**이나, **메모리 사용량이 특정 임계값에 도달했을 때**에 자동으로 수거 대상들을 수거합니다. 

수거 대상 : 도달 가능성이 없는 값. (도달 가능한 값 : 코드의 실행 흐름에서 어떤 방식으로든 참조할 수 있는 변수나 객체)
특정 시점 : 함수가 실행을 마치고 해당 콜스택에서 제거 될 때

**Comment by sryung1225** [comment]
가비지 컬렉터(garbage collector, GC)는 자신의 주소를 참조하는 변수의 개수(참조 카운트)가 0이 된 메모리 주소를 수거 대상으로 자동 수집합니다. 그리고 런타임 환경에 따라 특정 시점이나 메모리 사용량이 포화 상태에 임박할 때마다 자동으로 수거 대상들을 수거(collecting)합니다. 수거된 메모리는 다시 새로운 값을 할당할 수 있는 빈 공간이 됩니다.

**Comment by Stilllee** [comment]
가비지 컬렉터는 프로그래밍에서 메모리 관리를 자동화하는 시스템으로, 다음과 같이 작동합니다

#### 1. 참조 카운트
프로그램 내 각 데이터 객체에는 그 객체의 주소를 참조하는 변수의 수를 나타내는 '참조 카운트'가 있습니다. 변수나 다른 데이터 구조가 객체를 참조할 때마다 이 카운트는 증가하고, 참조가 해제되면 감소합니다.
    
#### 2. 수거 대상 식별 
참조 카운트가 0이 된 메모리 주소, 즉 더 이상 어떤 변수나 객체에 의해 참조되지 않는 데이터는 가비지 컬렉터의 수거 대상이 됩니다.  이것은 해당 데이터가 더 이상 필요하지 않다는 것을 의미합니다.
    
#### 3. 메모리 수거 및 재할당
가비지 컬렉터는 이러한 '수거 대상' 메모리를 자동으로 찾아내어 해제합니다. 수거된 메모리는 그 후 다시 프로그램에 의해 새로운 데이터를 저장할 수 있는 빈 공간으로 재활용됩니다.
    
#### 4. 자동화 및 최적화 
가비지 컬렉터는 런타임 환경에 따라 자동으로 작동합니다. 일반적으로 메모리 사용량이 포화 상태에 임박하거나 특정 시점에 도달했을 때 활성화되어, 메모리를 효율적으로 관리하고 시스템의 안정성을 유지합니다.

이러한 방식으로 가비지 컬렉터는 프로그램의 메모리 관리를 자동화하고 최적화하여, 개발자가 메모리 관리에 대해 걱정할 필요를 줄여줍니다.
