### ISSUE TITLE
2.3.1_let, const 키워드와 var 키워드의 차이점을 변수 호이스팅 관점에서 설명해주세요.

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/core-js#10]
📝 42p
❓ let, const 키워드와 var 키워드의 차이점을 변수 호이스팅 관점에서 설명해주세요.

아래의 예제 코드를 활용하거나 직접 예제 코드를 만들어서 설명해주세요.

1. let, const 키워드
```jsx
console.log(foo);
let foo;
```

2. 
```js
console.log(foo);
var foo;
```

**Comment by Stilllee** [comment]
`var`와 `let`, `const`로 선언된 변수는 선언문이 스코프 최상단으로 끌어올려지는 호이스팅이라는 공통점을 가지고 있습니다.

다만, 호이스팅 되었을 때의 초기화 여부에 따라 차이가 발생하게 됩니다.
### var 키워드
호이스팅 되었을 때, 변수는 `undefined`로 초기화 됩니다.
```js
console.log(fu); // (1) undefined

var fu = '푸바오';

console.log(fu); // (2) 푸바오
```
(1) : 선언만 끌어올려진 상태에서 변수에 접근하면 `undefined`를 출력합니다.
(2) : 실제 코드에 도달했을 때 변수의 초기화가 발생하며 이후에는 올바른 값이 출력됩니다.
<br>

### let, const 키워드
호이스팅 되었을 때, 변수 초기화는 되지 않습니다.

따라서, 변수 선언문에 도달했을 때까지는 값을 사용할 수 없으며 이때 변수에 접근하면 `ReferenceError`가 발생합니다. 
```js
console.log(rui); // ReferenceError: rui is not defined

let rui = '루이바오'; 
```

```js
console.log(hui); // ReferenceError: hui is not defined

const hui = '후이바오'; 
```
이처럼 변수가 선언되었으나 초기화되지 않은 상태를 임시 사각지대, TDZ(Temporal Dead Zone)라고 합니다.

실제 코드에 도달했을 때에는 변수의 초기화가 발생하여 올바른 값이 출력됩니다.
```js
let rui = '루이바오';
const hui = '후이바오';

console.log(`${rui}와 ${hui}`); // 루이바오와 후이바오
```
<br>

`let`과 `const`는 보다 엄격한 스코핑 규칙을 따르기 때문에, `var`보다 예측 가능하고 안전한 코드를 작성할 수 있게 도와줍니다.

**Comment by lulla-by** [comment]
let,const에 비해 var가 가지고 있는 특이점은 선언과 동시에 초기화가 이루어진다는 점입니다.

변수의 생성과정은 선언-> 초기화 -> 할당으로 이루어지는데 var는 선언과 동시에 자바스크립트 엔진이 undefined로 초기화를 진행합니다. 따라서 할당이 이루어지기도 전에 호이스팅이 가능합니다.

```js
console.log(foo);

var foo;
```
**결과: undefined 출력**

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/e5e6a20c-4ee4-4787-a480-280bf30be15e)


**반면 let, const는 할당 이전에는 참조가 불가능합니다. 만약 다음과 같이 할당 이전에 참조를 진행하면 레퍼런스 에러가 발생합니다.**

```js
console.log(hoistingLet)

let hoistingLet;

```

 **결과:ReferenceError**

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/49fc01be-317a-494f-b4a6-138906e88ded)

```js

console.log(hoistingConst)

**let hoistingConst;**
```

결과:ReferenceError

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/11437f51-a992-45f1-b9ad-f1b8f2f2800d)


+ 추가로 let과 const의 차이에 대해서 짧게 설명하도록 하겠습니다.
let은 재할당이 가능합니다. 따라서 다음과 같이 할당을 다시 해도 됩니다.

```js
let data = "data"

data = "new data"
```
![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/4550f344-0996-4229-bb27-69a47092d71f)



하지만 const는 재할당이 불가능합니다. 따라서 다음과 같이 재할당을 시도하면 에러가 발생합니다.
```js
const data = "data"

data = "new data"
```
![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/706ee809-b788-4b08-a81d-328654768b86)




참고로 var는 재할당과 재선언 모두 가능합니다. var로 인한 전역 오염을 막기 위해서 let과 const를 사용하는것이 권장됩니다.

**Comment by sryung1225** [comment]
**`let` `const` `var` 모두 변수 호이스팅은 이루어집니다.** 차이는 초기화 단계를 어떻게 거치냐에 있습니다.

자바스크립트 엔진은 변수 선언을 **선언 단계**와 **초기화 단계** 두 단계를 차례로 진행합니다.

`let` `const` 키워드는 선언 단계와 초기화 단계를 분리하여 진행하는데, 선언 단계는 런타임 이전에 실행되지만 초기화 단계는 해당 변수 선언문(`let foo`) 라인에서 실행됩니다. 때문에 변수 선언문이 적힌 라인에 오기 전에는 변수를 참조할 수 없는 구간(TDZ)에 빠진 상태이기 때문에 참조 에러가 발생합니다.

```jsx
console.log(foo);
let foo;
// 🚨 ReferenceError: 'foo' is not defined
```

`var` 키워드는 선언 단계와 초기화 단계를 한 번에 진행합니다. 때문에 변수 선언문이 적힌 라인에 오기 전에도 변수를 참조할 수 있으며, 최초 초기화가 진행된 `undefined` 가 출력됩니다.

```jsx
console.log(foo);
var foo;
 // ? undefined
```

동일한 예제로 블로그 포스팅한 경험이 있어 참고차 관련 링크 첨부해둡니다 😊 ([https://s-ryung.tistory.com/79#let%2C const와 변수 호이스팅-1](https://s-ryung.tistory.com/79#let%2C%20const%EC%99%80%20%EB%B3%80%EC%88%98%20%ED%98%B8%EC%9D%B4%EC%8A%A4%ED%8C%85-1))

**Comment by chaehaeun** [comment]
**var : 선언과 초기화가 동시에 이루어지고 재할당이 가능**
```js
console.log(foo); // undefined
var foo = 'bar';
console.log(foo); // 'bar'
```

**let : 선언과 초기화가 분리되어 진행. 재할당 가능**

**const : 선언과 초기화가 분리되어 진행. 재할당 불가능**
```js
console.log(foo); // ReferenceError: Cannot access 'foo' before initialization
let foo = 'bar';
console.log(foo); // 'bar'
```


**셋 다 호이스팅이 일어나지만**

**var는 선언과 초기화가 동시에 이루어지기 때문에 선언 이전에 호출해도 undefined라는 값을 참조 가능**

**let const는 선언과 초기화가 분리되어 일어나기 때문에 선언 이전에 호출하면 레퍼런스 에러를 일으킴.**

**해당 스코프 최상단에서부터 변수 선언 이전까지 let과 const를 참조할 수 없는 구간을 템퍼럴 데드 존이라고 부름**

**Comment by eeeyooon** [comment]
var 키워드로 선언한 변수와 달리 let 키워드로 선언한 변수는 변수 호이스팅이 발생하지 않는 것처럼 동작합니다.

```jsx
console.log(foo); // ReferenceError: foo is not defined
let foo;
```

var 키워드였다면 변수 호이스팅에 의해 런타임 이전에 변수가 선언되어 undefined를 출력해야 합니다. 하지만 let 키워드에서는 참조에러가 나타납니다.

let 키워드로 선언한 변수는 '선언 단계'와 '초기화 단계'가 분리되어 진행됩니다. 즉, 런타임 이전에 자바스크립트 엔진에 의해 암묵적으로 선언 단계가 먼저 실행되지만 초기화 단계는 변수 선언문에 도달했을 때 실행됩니다. 만약 초기화 단계가 실행되기 이전에 변수에 접근하려고 하면 참조 에러가 발생합니다.

let 키워드로 선언한 변수는 스코프의 시작 지점부터 초기화 단계 시작 지점(변수 선언문)까지 변수를 참조할 수 없습니다. 스코프의 시작 지점부터 초기화 시작 지점까지 변수를 참조할 수 없는 구간을 **일시적 사각지대(TDZ: Temporal Dead Zone)** 라 부릅니다.


```js
// 런타임 이전에 선언 단계가 실행된다. 아직 변수가 초기화되지 않았다.
// 초기화 이전의 일시적 사각 지대에서는 변수를 참조할 수 없다.
console.log(foo); // ReferenceError: foo is not defined
let foo;
```

```js
let foo; // 변수 선언문에서 초기화 단계가 실행된다.
console.log(foo); // undefined

foo = 1; // 할당문에서 할당 단계가 실행된다.
console.log(foo); // 1
```

```js
// 변수 호이스팅에 의해 런타임 이전에 변수가 선언되어 undefined를 출력한다.
console.log(foo);
var foo; // undefined
```
