### ISSUE TITLE
2.3.2_두 코드의 console.log()의 값이 서로 다르게 나오는 이유를 스코프체인과 연결하여 설명해주세요.

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/core-js#11]
📝 p54
❓ 이 두 코드는 변수 선언 방식과 이름만 다를 뿐 구조는 거의 동일합니다. 하지만 내부에 찍힌 console.log()의 값은 서로 다른 것을 확인할 수 있는데요. 이러한 결과가 나오는 이유를 스코프 체인과 연결 시켜 작성해주세요.

1번 코드
```js
var a = 1;
var outer = function() {
var inner = function() {
console.log("a: ",a);  // "a:  undefined"
var a = 3;
};
inner();
};
outer();
```

2번 코드
```js
let b = 1;
let outerB = function() {
let innerB = function() {
console.log("b: ",b);  // "b:  1"
b = 3;
};
innerB();
};
outerB();
```

**Comment by eeeyooon** [comment]
**1번 코드**

이 코드에서 `var` 키워드로 선언된 변수 a는 함수  inner 내에서 호이스팅되어 처리됩니다. inner 함수의 스코프 내에서 `var a = 3;`이 선언되었기 때문에, JavaScript 엔진은 inner 함수의 최상단으로 `var a;` 선언을 호이스팅합니다. 그러나 이때 a는 아직 `undefined`로 초기화되어 있으며, 3은 할당되지 않았습니다.

따라서 `console.log("a: ", a);`가 실행될 때, inner 함수의 지역 변수 a는 이미 호이스팅되어 선언되었지만 아직 `undefined` 값이 할당된 상태입니다. 이는 outer 함수나 전역 스코프의 a와는 별개의 지역 변수입니다. inner 함수 내에서의 지역 변수 a는 inner 함수 스코프에 속하므로 외부 스코프의 a에 접근할 수 없습니다.

**2번 코드**

반면, `let` 키워드를 사용하여 선언된 변수 b는 블록 스코프를 가지며 호이스팅의 동작 방식이 1번의 `var`와 다릅니다. `let`으로 선언된 변수는 호이스팅되지만 TDZ(Temporal Dead Zone)에 의해 선언 전에는 접근할 수 없습니다. 그러나 innerB 함수 내에서 별도의 b 변수가 선언되지 않았습니다.
따라서 innerB 함수에서 `console.log("b: ", b);`를 호출할 때, innerB 스코프 내에 b가 없으므로 스코프 체인을 통해 상위 스코프인 전역 스코프의 b값을 참조하게 됩니다. 이 때 전역 스코프에 선언된 b의 값은 1이므로, `console.log`는 `"b: 1"`을 출력합니다.

결과적으로, 1번 코드와 2번 코드의 차이는 `var`와 `let`의 스코프 및 호이스팅 동작의 차이에서 발생합니다.

**Comment by Stilllee** [comment]
### 스코프와 스코프 체인
스코프란 식별자의 유효 범위를 의미하며, 식별자의 유효 범위를 검색하는 과정을 스코프 체인이라고 합니다.

스코프 체인을 가능하게 하는 것은 `LexicalEnvironment`의 수집 자료인 `outerEnvironmentReference`로, 이를 통해 내부 스코프에서 외부 스코프의 변수나 함수를 참조할 수 있습니다.

이 때,  `outerEnvironmentReference`는 함수가 선언될 당시의 `LexicalEnvironment`를 참조합니다.
<br>

### 1번
`inner`함수의 `LexicalEnvironment`에서 변수 `a`를 찾을 때, `inner`함수 내부에서 `var a = 3;`으로 인해 변수 `a`가 호이스팅되어 `undefined`로 초기화 된 상태입니다. 

따라서 `console.log("a: ", a);`를 실행할 때, `a`의 값은 `undefined`로 출력됩니다.

### 2번
`innerB`함수의 `LexicalEnvironment`에서 변수 `b`를 찾을 때, `innerB`함수 내부에서 `b`를 새로 선언하지 않고, 전역 스코프에 있는 `b`에 값을 재할당 합니다. 

재할당하기 전에 `console.log("b: ", b);`를 실행하므로,  `innerB`의 `outerEnvironmentReference` 즉, 전역의 `LexicalEnvironment`를 통해 찾은 `b`의 값인 1을 출력됩니다.

**Comment by sryung1225** [comment]
스코프 체인은 코드 내에서 변수에 접근할 때 현재 스코프에서 해당 변수를 찾고, 없으면 상위 스코프로 올라가며 찾는 과정을 말합니다.

1번 코드의 경우 `var` 키워드로 선언된 변수 `a` 가 `inner()` 내에서 호이스팅되어 함수의 최상단으로 끌어올려 집니다. 때문에 선언이 완료된 상태이므로 출력 결과가 `undefined` 가 됩니다.

2번 코드의 경우 `let` 키워드로 선언된 변수 `b` 는`innerB()` 에서 찾을 수 없기 때문에 스코프 체인을 따라 상위 스코프에서 `b` 를 찾기 위해 `outerB()` 그리고 전역으로 올라가게 됩니다. 전역에 `b` 는 1로 값이 할당되어 있기 때문에 출력 결과가 `1` 이 됩니다.

**Comment by chaehaeun** [comment]
1번 코드
var 키워드로 선언한 a가 inner() 내부에서 호이스팅되었기 때문에 undefined 출력

2번 코드
1번과 다르게 2번은 재선언이 아닌 재할당이기 때문에 호이스팅 되지 않음. 그렇기 때문에 스코프체인을 통해 전역에 있는 b값을 찾아 1 출력

**Comment by lulla-by** [comment]
**스코프체인은 변수를 참조할 때 현재 스코프부터 시작하여 `outerEnvironmentReference`를 따라 올라가며 변수를 찾는 메커니즘입니다.**

1번 코드의 경우 `var`를 사용하여 변수를 선언했는데 `var`의 대표적인 특징은 재선언 및 재할당이 가능하다는 점입니다. 따라서 내부에 var로 재선언된 `a`는 초기화로 `undefined`가 할당되고 호이스팅도 됩니다. 따라서 1번 코드 내부의 `console.log("a: ",a)`에서의 `a`는 현재 스코프내에서 호이스팅된 `var a = 3;`을 참조하게 됩니다. 하지만 선언 이전에 참조하였으므로 호이스팅된 `a`의 초기화 값인 `undefined`가 출력됩니다.

반면 2번 코드에서는 `b`를 `let`키워드로 선언했습니다. `let` 키워드의 경우 실제 선언 전에 호출시에는 참조가 되지 않는다는 특징이 있습니다. 

<수정 답변>

스코프 체인은 변수를 참조할 때 현재 스코프부터 시작하여 현재 스코프에 해당 변수가 없을 경우 상위로 올라가며 변수를 찾는 메커니즘이라고 설명했는데요. 

여기에서는 b를 재선언하지않고 재할당을 했습니다. `outerEnvironmentReference`는 해당 변수가 선언된 위치를 찾아가기 때문에  b가 선언된 위치를 찾기 위해 스코프체인을 타고 상위로 올라가게 됩니다.

그리하여 맨 처음 `let`키워드로 할당한 `let b = 1`를 참조하게 되고 `console.log("b: ",b)`의 변수 b는 상위에 선언된 b를 참조하게 됩니다.


+만약 innerB내부의 b가 `let b = 3`으로 재선언 된다면 이때는 호이스팅이 발생하게 됩니다.  `let`과 `const`모두 호이스팅이 되지만 `TDZ`에 가려져서 호이스팅이 되지 않는것처럼 보일 뿐입니다. 이럴 경우에는 TDZ가 발생하며 ReferenceError를 발생시킵니다.

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/badb0aac-a2da-4cb3-ad4d-efb59e9fda99)
