### ISSUE TITLE
3.1.3_함수 내부의 this 바인딩을 변경하는 방법

### ISSUE THREAD

**Issue by Stilllee** [Coding-Village-Protector/core-js#12]
📝 74p
❓ 함수 내부의 this 바인딩을 변경하는 방법
```js
var a = "global!";
var obj = {
  a: "object!",
  b: function() {
    console.log(this.a); // object!

    function c() {
      console.log(this.a); // global!
    }
    c();
  }
}
obj.b();
```
위 코드에서 메서드 `b`의 `this`는 `obj`객체를 가리킵니다. 그러나 `b`메서드 내부에 정의된 `c`함수는 일반 함수로 호출되므로, `this`가 전역 객체를 가리키게 됩니다.

만약, `c`의 `this`가 전역객체가 아닌 `obj`를 바라보게 하려면 어떻게 해야할까요?

여러 방법 중 한 가지를 선택하고 예시코드와 함께 설명해주세요.

**Comment by chaehaeun** [comment]
`c`를 화살표 함수로 정의하게 되면 `c` 함수 내부의 `this`가 `obj` 객체를 가리키게 됩니다.

```js
var a = "global!";
var obj = {
  a: "object!",
  b: function() {
    console.log(this.a);

    const c = () => {
      console.log(this.a);
    }
    c();
  }
}
obj.b();
```
화살표 함수는 자신만의 `this`를 가지지 않기 때문에 자신이 선언된 렉시컬 스코프의 `this` 값을 상속 받습니다. 따라서 화살표 함수로 선언된 `c`는 `b`의 `this`를 상속 받아 `obj`를 가리키게 됩니다.

**Comment by eeeyooon** [comment]
제가 선택한 방법은 bind 메서드를 사용하는 것입니다. bind는 새로운 함수를 생성하며, 이 함수의 this를 메서드에서 전달된 첫 번째 인수로 설정합니다. 따라서 bind를 사용하면 내부 함수 c의 this 값을  b의 this과 동일하게 obj를 바라보게 할 수 있습니다.

```js
var a = "global!";
var obj = {
  a: "object!",
  b: function() {
    console.log(this.a); // object!

    var c = function() {
      console.log(this.a); // object!
    }.bind(this);

    c();
  }
}
obj.b();

```

**Comment by lulla-by** [comment]
위에 답변해주신 분들께서 화살표 함수와 `bind` 메서드를 활용하는 방법을 설명해주셔서 저는 변수를 활용하여 우회하는 케이스로 접근해봤습니다.

해당 방식은 es5까지 자체적으로 내부 함수에 `this`를 상속할 방법이 없을 때 사용한 방식으로 살짝 허무하지만 기대한대로 작동합니다.

```js
var a = "global!";
var obj = {
  a: "object!",
  b: function() {
    console.log(this.a); // object!

    var self = this;

    function c() {
      console.log(self.a); // object!
    }
    c();
  }
}
obj.b();
```

**Comment by Stilllee** [comment]
#### 1. 변수명을 이용한 우회
`this`를 다른 변수에 할당하고 내부 함수에서 이 변수를 사용하는 방식으로, `this`의 값이 함수가 선언될 때 결정되는 것을 활용합니다.
일반적으로는 `self`, `that`, `_this`, `_` 등의 변수명을 사용합니다.
```js
var a = "global!";
var obj = {
  a: "object!",
  b: function() {
    var self = this;
    console.log(this.a); // object!

    function c() {
      console.log(self.a); // object!
    }
    c();
  }
}
obj.b();
```

#### 2. 화살표 함수
ES6에서 도입된 화살표 함수는 자체적인 `this`바인딩을 갖지 않고, 상위 스코프의 `this`를 그대로 사용합니다. 
```js
var a = "global!";
var obj = {
  a: "object!",
  b: function() {
    console.log(this.a); // object!

    const c = () => {
      console.log(this.a); // object!
    }
    c();
  }
}
obj.b();
```

#### 3. call / apply
`call` 또는 `apply` 메서드를 사용하여 함수를 호출하면서 `this` 값을 명시적으로 바인딩 할 수 있습니다. 
```js
var a = "global!";
var obj = {
  a: "object!",
  b: function() {
    console.log(this.a); // object!

    function c() {
      console.log(this.a); // object!
    }
    c.call(this);
  }
}
obj.b();
```

#### 4. bind
`bind`메서드를 사용하여 함수의 `this`를 고정시킬 수 있습니다. 이렇게 하면 함수가 어디에서 호출되더라도 `this`는 `bind`에 전달된 객체를 가리킵니다.
```js
var a = "global!";
var obj = {
  a: "object!",
  b: function() {
    console.log(this.a); // object!

    function c() {
      console.log(this.a); // object!
    }.bind(this);
    c();
  }
}
obj.b();
```
