### ISSUE TITLE
3.2.4_메서드의 this와 메서드 내부의 콜백 함수의 this 불일치 문제를 해결 후 설명해주세요.

### ISSUE THREAD

**Issue by chaehaeun** [Coding-Village-Protector/core-js#13]
📝 89p
❓ 메서드의 this와 메서드 내부 콜백 함수의 this 불일치 문제를 해결 후 설명해주세요.
```js
const myObj = {
  myProperty: 'Hello, world!',
  outerFunc: function() {
    console.log(this.myProperty); // 'Hello, world!'
    setTimeout(function innerFunc() {
      console.log(this.myProperty); // undefined
    }, 1000);
  }
};

myObj.outerFunc();
```
현재 `innerFunc` 함수 내부에서의 `this.myProperty`는 `undefined`를 출력합니다. 
이는 `innerFunc`가 `myObj` 객체의 컨텍스트를 `this`로 가지지 않기 때문입니다.

`innerFunc` 내에서 `this.myProperty`가 `myObj.myProperty`를 정확히 참조하도록 하려면 코드를 어떻게 수정해야 할까요? 

코드를 수정한 후 **(1)`innerFunc`가 왜 `undefined`를 출력했는지**와 **(2)이 문제를 해결한 방법**, 두 가지에 대해 설명해주세요.

**Comment by eeeyooon** [comment]
```js
const myObj = {
  myProperty: 'Hello, world!',
  outerFunc: function() {
    console.log(this.myProperty); // 'Hello, world!'
    setTimeout(() => { //
      console.log(this.myProperty); // 'Hello, world!'
    }, 1000);
  }
};

myObj.outerFunc();
```
(1) 기존 코드 innerFunc에서 this.myProperty가 `undefined`를 출력한 이유는 `setTimeout`에 의해 호출된 일반 함수 내에서의 `this`는 전역 객체를 가리키기 때문입니다. 이때 myProperty는 전역 객체가 아니기 때문에 undefined가 됩니다.

(2) setTimeout의 콜백 함수를 일반 함수(innerFunc)에서 화살표 함수로 변경하여 해결했습니다. 이 화살표 함수는 outFunc의 this를 상속받으므로, this.myProperty는 myObj의 myProperty를 참조하게 됩니다.

**Comment by Stilllee** [comment]
### (1) : `innerFunc`에서 `undefined` 출력의 이유
문제 코드에서 `innerFunc`는 `setTimeout`내의 콜백 함수로 사용되었습니다. 

자바스크립트에서 `setTimeout`과 같은 내장 함수 내에서 일반 함수로 호출되는 콜백함수의 `this`는 기본적으로 전역 컨텍스트를 가리킵니다.

따라서, 전역 스코프에는 `myProperty`라는 이름의 속성이 존재하지 않기 때문에 `undefined`를 반환하는 것입니다.
<br>

### (2) : `bind`메서드로 문제 해결
```js
const myObj = {
  myProperty: "Hello, world!",
  outerFunc: function () {
    console.log(this.myProperty);
    setTimeout(
      function innerFunc() {
        console.log(this.myProperty);
      }.bind(this),
      1000
    );
  },
};

myObj.outerFunc();
```
`bind`메서드를 사용하여 `innerFunc`의 `this`를 `outerFunc`의 `this`인 `myObj`객체로 명시적으로 설정했습니다.

`.bind(this)`를 호출함으로써 `innerFunc`내의 `this`는 항상 `outerFunc`가 호출될 때의 컨텍스트인 `myObj`객체를 가리키게 됩니다.

따라서, `myObj`의 `myProperty`속성을 정확히 참조하여 `"Hello, world!"`를 출력합니다.

**Comment by lulla-by** [comment]
(1) innerFunc가 왜 undefined를 출력했는지

콜백 함수 내부에서의 `this`는 콜백함수의 제어권을 가진 함수가 `this`를 어떻게 정했는지에 따라 `this`가 달라집니다. 만약 `this`를 설정하지 않은 상황이라면 콜백함수는 기본적으로 전역 객체를 바라봅니다. 콜백함수 내부에서 `this.myProperty`를 호출했는데 이때 `this`는 전역 객체를 바라봅니다. 따라서 미리 전역 객체에 `myProperty`를 선언 및 할당하지 않는 이상 `undefined`가 출력됩니다.

(2) 이 문제를 해결한 방법

저는 `apply` 메서드를 사용하여 setTimout 내부의 콜백 함수가 `myObj`를 `this`로 바라보도록 설정했습니다.

```js
const myObj = {
  myProperty: 'Hello, world!',
  outerFunc: function() {
    console.log(this.myProperty); // 'Hello, world!'
    setTimeout(function innerFunc() {
      console.log(this.myProperty); // 'Hello, world!'
    }.apply(this), 1000);
  }
};

myObj.outerFunc();
```

**Comment by chaehaeun** [comment]
```js
const myObj = {
  myProperty: 'Hello, world!',
  outerFunc: function() {
    console.log(this.myProperty); // 'Hello, world!'
    setTimeout((function innerFunc() {
      console.log(this.myProperty); // 'Hello, world!'
    }).bind(this), 1000);
  }
};

myObj.outerFunc();
```

### 1. innerFunc가 undefined를 출력한 이유: 
`setTimeout` 내부에서 호출되는 함수는 기본적으로 전역 컨텍스트에서 실행됩니다. 따라서 `this`는 전역 객체를 가리키게 되고, `myObj`와는 무관한 컨텍스트가 되기 때문에 `this.myProperty`는 `undefined`를 반환합니다.

### 2. 이 문제를 해결한 방법
`bind`를 사용하여 `innerFunc` 함수의 `this`를 `outerFunc`의 `this`에 명시적으로 바인딩했습니다. `.bind(this)`는 `outerFunc`가 호출될 때의 `this`, 즉 `myObj`를 `innerFunc`의 `this`에 고정시킵니다. 이렇게 하면 `setTimeout` 내부에서 실행되더라도 `innerFunc`의 `this`가 `myObj`를 정확히 가리키게 되어 `this.myProperty`가 정상적으로 'Hello, world!'를 출력하게 됩니다.
