### ISSUE TITLE
3._this는 언제 결정되는지, 화살표 함수의 this는 어떤 특징이 있는지 설명해주세요.

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/core-js#14]
📝 65p
❓ 다음에서 제시하는 this 관련 단답형 문제 4개에 대해 간단한 답변을 작성해주세요. 책 내용을 바탕으로 간단하게 작성해주세요.

1. this는 언제 결정되나요?

2. 프로그래밍 언어에서 함수와 메서드는 미리 정의한 동작을 수행하는 코드 뭉치입니다. 이 둘을 구분하는 유일한 차이는 무엇일까요? 또한 "함수로서의 호출"과 "메서드로서 호출"을 어떻게 구분하는지 말씀해주세요.

3. 생성자(클래스)와 인스턴스는 무엇인가요?

4. 화살표 함수의 this는 어떤 특징을 가지고 있나요?

**Comment by Stilllee** [comment]
1.  자바스크립트에서 `this`는 실행 컨텍스트가 생성될 때 즉, **함수가 호출될 때** 결정되며 어떻게 호출되는지에 따라 `this`의 값이 달라집니다.
2. 함수가 변수나 상수에 할당되어 독립적으로 호출되는 것은 **함수로서의 호출**이고, 객체의 프로퍼티에 할당되어 해당 객체의 컨텍스트에서 호출되는 것을 **메서드로서의 호출**입니다.
3. **클래스**는 어떤 공통된 성질을 지니는 객체들을 생성하는데 사용하는 함수이고, 클래스를 통해 만든 객체를 **인스턴스**라고 합니다.
4. 화살표 함수는 자신만의 `this`를 생성하지 않고, 자신이 생성된 그 스코프의 `this`를 사용합니다. 즉, 화살표 함수 내에서의 함수는 독립적인 기능을 수행하는 반면, 메서드는 객체와 연관된 동작을 수행합니다. `this`는 항상 외부 함수의 `this`와 같습니다.

**Comment by lulla-by** [comment]
1. `this`는 함수를 호출할 때 결정됩니다.

2. 둘을 구분하는 차이는 **독립성**입니다. 함수는 함수 그 자체로서 호출되는 것이지만 메서드는 자신을 호출한 대상에 대하여 함수를 실행하게 됩니다. 이 둘을 구분하는 대표적인 방법으로는 .과 대괄호 표기법으로 함수 앞에 자신을 호출한 객체가 있는 경우 메서드가 됩니다.


3. `class`는 구체적인 인스턴스를 만들기 위한 일종의 틀입니다. 인스턴스는 생성자 함수를 사용하여 생성된 객체입니다.

4. 화살표 함수는 `this` 바인딩의 과정 자체가 생략되어 있습니다. 따라서 내부에 `this`값이 존재하지 않으며 접근하고자 할 경우 스코프체인상 가장 가까운 `this`에 접근하게 됩니다.

**Comment by chaehaeun** [comment]
1. 함수나 메서드가 호출될 때 결정됩니다.

2. 함수와 메서드의 유일한 차이는 메서드가 클래스의 인스턴스나 객체에 종속되어 있음입니다. "함수로서의 호출"은 독립적으로 호출되며, "메서드로서의 호출"은 객체의 속성으로 호출됩니다.

3. 생성자 함수는 어떤 공통된 성질을 지니는 객체들을 생성하는 데 사용하는 함수입니다. 그리고 그 생성자 함수를 통해 만든 객체를 인스턴스라고 합니다.

4. 화살표 함수는 자신만의 this가 없기 때문에 언제나 상위 스코프의 this를 참조하는 특징을 가지고 있습니다.

**Comment by eeeyooon** [comment]
### 1.  this는 언제 결정되나요?
기본적으로 실행 컨텍스트가 생성될 때 함께 결정됩니다. 실행컨텍스트는 함수를 호출할 때 생성되므로, 바꿔말하면 this는 함수를 호출할 때 결정된다고 할 수 있습니다.

<br/>

### 2.  프로그래밍 언어에서 함수와 메서드는 미리 정의한 동작을 수행하는 코드 뭉치입니다. 이 둘을 구분하는 유일한 차이는 무엇일까요? 또한 "함수로서의 호출"과 "메서드로서 호출"을 어떻게 구분하는지 말씀해주세요.

**독립성**. 함수는 그 자체로 독립적인 기능을 수행하는 반면, 메서드는 자신을 호출한 대상 객체에 관한 동작을 수행합니다. 자바스크립트는 상황 별로 this 키워드에 다른 값을 부여하게 함으로써 이를 구현했습니다.

‘함수로서 호출’과 ‘메서드로서 호출’을 **점(.)의 유무**로 구별할 수 있습니다. 앞에 점이 없으면 함수로서 호출한 것(`func(1);`)이고, 앞에 점이 있으면 메서드로서 호출한 것(`obj.method(2);`)입니다. 덧붙여, 대괄호 표기법에 따른 경우(`obj[’method’](2)`)도 메서드로서 호출한 것입니다.

정리하자면, 점 표기법이든 대괄호 표기법이든 어떤 함수를 호출할 때 그 함수 이름(프로퍼티명) 앞에 객체가 명시되어 있는 경우에는 메서드로 호출한 것이고, 그렇지 않은 모든 경우는 함수로 호출한 것입니다."

<br/>

### 3.  생성자(클래스)와 인스턴스는 무엇인가요?
클래스를 통해 만든 객체를 인스턴스라고 합니다. 생성자는 구체적인 인스턴스를 만들기 위한 일종의 틀입니다. 이 틀에는 해당 클래스의 공통 속성들이 미리 준비되어있고, 여기에 구체적인 인스턴스의 개성을 더해 개별 인스턴스를 만들 수 있습니다.

- 생성자 = 기본 붕어빵 반죽, 굽기에 알맞은 온도와 시간이 설정된 붕어빵 틀
- 인스턴스의 개성 = 피자치즈, 슈크림, 팥
- 개별 인스턴스 = 슈붕, 팥붕, 피붕

<br/>

### 4.  화살표 함수의 this는 어떤 특징을 가지고 있나요?
화살표 함수는 실행 컨텍스트를 생성할 때 this 바인딩 과정 자체가 빠지게 되어, 상위 스코프의 this를 그대로 활용할 수 있습니다. (ES5 환경에서는 화살표 함수를 사용할 수 X)

<br/>
