### ISSUE TITLE
4.5_비동기 코드에 대해 설명해주세요.

### ISSUE THREAD

**Issue by chaehaeun** [Coding-Village-Protector/core-js#16]
📝 p106
❓ 동기적인 코드는 현재 실행 중인 코드가 완료된 후에 다음 코드를 실행하는 방식입니다. 그렇다면 비동기적인 코드는 **1)어떠한 방식**인지, **2) 비동기 코드의 예시로 어떤 것이 있는지** 설명해주세요.

**Comment by Stilllee** [comment]
**비동기**
프로그래밍에서 작업을 처리하는 단위를 **스레드**라고 부르는데요, 자바스크립트는 기본적으로 단일 스레드로 작동하기 때문에 멀티 스레드 방식과 같이 여러 작업을 동시에 수행하는 것이 불가능합니다.

이러한 제약을 극복하기 위해 자바스크립트에서는 비동기 처리를 사용합니다. 비동기 처리는 특정 작업의 완료를 기다리지 않고 다른 작업을 진행하는 방식을 말하며, 하나의 스레드에서 여러 작업을 효율적으로 관리할 수 있게 해줍니다.

<br>

**비동기 처리의 예시**
비동기 처리의 대표적인 예시로는 `setTimeout`, `addEventListener`, `XMLHttpRequest` 
 등이 있습니다. 
 
이런 함수들은 작업의 실행이 완료되기를 기다리는 대신, 특정 작업(ex: 타이머, 이벤트 응답, HTTP 요청)이 완료될 때까지 기다리지 않고 다른 코드의 실행을 계속 진행할 수 있게 해줍니다.
 
 <br>
 
이전에 관련 내용을 정리해둔 글이 있어 첨부합니다 😸
🔗 [비동기 처리](https://woodstock.hashnode.dev/67me64z6riwioyymoumra?source=more_series_bottom_blogs)

**Comment by lulla-by** [comment]
**1) 비동기 코드의 방식**

동기와 비동기는 자바스크립트에서 중요한 부분인데요. 어떤 코드를 실행할 때 실행 순서에 따라서 해당 코드가 완료되기 전까지 다음 코드로 진행이 안되는 것을 동기라하고 반면에 어떤 코드가 실행중일때 다른 코드를 실행하는 것을 비동기라 합니다. 

비동기 코드는 큐로 관리됩니다. 큐는 콜백큐(태스크 큐)와 마이크로 태스크 큐로 나뉩니다.

 콜백큐에서는 setTimeout에서 사용한 콜백함수들이 관리되고 마이크로 태스크 큐는 promise나 async/await의 결과물로 실행되어야 하는 코드가 담깁니다.

두 개의 큐 모두 이벤트 루프를 통해 관리되며 일반적으로 마이크로 태스크 큐가 콜백큐보다 우선순위에 있어 콜스택이 비어있을 경우 이벤트 루프가 마이크로 태스크 큐를 먼저 콜스택에 넣고 이후에 콜스택이 비워지면 콜백큐의 함수를 콜스택에 올립니다.

**2) 비동기 코드 예시**

비동기 코드 예시로는 setTimeout, promise, async/await 등이 있습니다.

**Comment by eeeyooon** [comment]
비동기적인 코드는 현재 실행 중인 코드의 완료 여부와 무관하게 즉시 다음 코드로 넘어갑니다. 사용자의 요청에 의해 특정 시간이 경과되기 전까지 어떤 함수의 실행을 보류한다거나(setTimeout), 웹브라우저 자체가 아닌 별도의 대상에 무언가를 요청하고 그에 대한 응답이 왔을 때 비로소 어떤 함수를 실행하도록 대기하는 등 (XMLHttpRequest), 별도의 요청, 실행 대기, 보류 등과 관련된 코드가 바로 비동기적인 코드의 예시입니다.

**Comment by sryung1225** [comment]
1) **비동기적인 코드**는 **어떠한 요청을 보내면 그 요청이 끝날 때까지 기다리는 것이 아닌, 응답에 관계없이 바로 다음 코드를 실행하는 방식**입니다. 흐름을 멈추지 않기 때문에 동시에 여러 가지 작업을 처리할 수 있습니다. **별도의 요청**, **실행 대기**, **보류** 등과 관련된 코드가 이에 해당합니다.

2) 비동기 코드의 예시로 setTimeout, addEventListener, XMLHttpRequest 등이 있습니다.

- `setTimeout` : 사용자의 요청에 의해 특정 시간이 경과되기 전까지 어떤 함수의 실행을 보류
- `addEventListener` : 사용자의 직접적인 개입이 있을 때 비로소 어떤 함수를 실행하도록 대기
- `XMLHttpRequest` : 웹 브라우저 자체가 아닌 별도의 대상에 무언가를 요청하고 그에 대한 응답이 왔을 때 비로소 어떤 함수를 실행하도록 대기

**Comment by chaehaeun** [comment]
### 1. 비동기 코드의 방식
비동기적인 코드는 현재 실행 중인 코드의 완료를 기다리지 않고 다음 코드를 실행하는 방식입니다.

### 2. 비동기 코드의 예시
- **웹 API 요청** : 웹 페이지에서 서버에 데이터를 요청하고 응답을 기다리는 과정은 비동기적으로 처리됩니다. 이를 통해 서버로부터 응답을 기다리는 동안에도 사용자는 웹 페이지를 자유롭게 탐색할 수 있습니다.
- **`setTimeout/setInterval`** : 이 함수들을 사용하면 지정된 시간이 지난 후에 함수를 실행할 수 있으며, 해당 시간 동안 프로그램은 다른 작업을 계속해서 수행할 수 있습니다.
- **이벤트리스너** :  애플리케이션은 이벤트가 발생하기를 기다리는 동안 다른 작업을 계속 수행할 수 있으며, 이벤트가 발생하면 등록된 이벤트 리스너가 호출됩니다.
- **파일 읽기/쓰기 (Node.js)**: Node.js에서 파일 시스템에 접근하는 작업은 일반적으로 비동기적으로 수행됩니다. 이는 파일 입출력 작업 동안 이벤트 루프가 블로킹되지 않도록 하여, 다른 요청을 동시에 처리할 수 있게 합니다.
