### ISSUE TITLE
4.3_콜백함수와 this

### ISSUE THREAD

**Issue by Stilllee** [Coding-Village-Protector/core-js#17]
📝 102p
❓ 다음 예제 코드에서 `studyTeam`의 메서드인 `displayMembers` 를 호출했을 때, `organization` 의 값이 다르게 출력되는 이유를 설명해보세요.

```js
var organization = "대한민국";
var members = ["짱구", "유리", "철수", "훈이", "맹구"];

var studyTeam = {
    organization: "코딩 마을 방범대",
    displayMembers: function(member) {
        if(this.displayMembers) {
            console.log(`${this.organization} 소속 ${member} 요원`);
        } else {
            console.log(`${this.organization} 국민 ${member}`);
        }
    }
};
studyTeam.displayMembers("짱구");
members.forEach(studyTeam.displayMembers);
```

**Comment by lulla-by** [comment]
```js
studyTeam.displayMembers("짱구");
```

이 부분에서는 displayMembers가 studyTeam이라는 객체의 메서드로 호출이 되었습니다. 따라서 this가 studyTeam으로 바인딩 되어 displayMembers라는 메서드가 내부에 있기 때문에 `코딩 마을 방범대 소속 짱구 요원`이 출력됩니다.

```js
members.forEach(studyTeam.displayMembers,studyTeam);
```
반면 foreach로 members의 내부 요소를 순회하며 studyTeam.displayMembers를 실행시킬 때는 this가 전역객체를 바라보게 됩니다. 해당 메서드가 forEach의 콜백함수로 사용되었기 때문인데 일반적으로 콜백함수는 this는 전역객체를 바라봅니다.

따라서 this는 전역을 의미하고 전역객체에는 displayMembers가 없기 때문에 else 구문이 호출됩니다. 이후 전역객체에서 var로 선언된 organization이 사용되어 `대한민국의 국민 짱구`의 형식으로 출력됩니다.

만약 this를 studyTeam으로 바인딩 하고 싶을 경우에는 다음과 같이 forEach 사용시에 thisArg를 지정하여 넘겨주면 studyTeam이 바인딩됩니다.
```js
members.forEach(studyTeam.displayMembers,studyTeam);```

**Comment by chaehaeun** [comment]
```
studyTeam.displayMembers("짱구");
```
는 `studyTeam` 객체의 `displayMembers` 메서드를 직접 호출하기 때문에 `this`는 객체 `studyTeam`을 가리킵니다. 따라서 `"코딩 마을 방범대 소속 짱구 요원"`이 출력됩니다.

```
members.forEach(studyTeam.displayMembers);
```
반면 `studyTeam.displayMembers` 함수는 `forEach`에 의해 일반 함수처럼 호출되며, 특정 객체에 바인딩되지 않습니다. 따라서 `this.organization`은 전역 변수 `organization`을 가리키게 되어 `"대한민국 소속 짱구 요원"`이 출력됩니다.

**Comment by sryung1225** [comment]
```tsx
studyTeam.displayMembers("짱구");
// ? 코딩 마을 방범대 소속 짱구 요원
```

위의 경우, `this` 가 `studyTeam` 으로 바인딩 되어 `displayMembers` 메서드 내부에 있기 때문에 `this.displayMembers` 가 존재하고 `organization` 이 “코딩 마을 방범대”로 출력됩니다.

```tsx
members.forEach(studyTeam.displayMembers);
// ? 대한민국 국민 짱구
// ? 대한민국 국민 유리
// ? 대한민국 국민 철수
// ? 대한민국 국민 훈이
// ? 대한민국 국민 맹구
```

위의 경우, `forEach` 를 이용해 `members` 의 내부를 순회하며 실행하기 때문에 `this` 가 전역객체를 바라보게 됩니다. 때문에 `this.displayMembers` 는 undefined이며 `organization` 이 “대한민국”으로 출력됩니다.

**Comment by eeeyooon** [comment]
`studyTeam.displayMembers("짱구");`에서 this가 studyTeam로 바인딩이 되어있습니다. 그렇기 때문에 displayMemebers 존재하여 “코딩 마을 방범대 소속 짱구 요원”이 출력됩니다.

반면 `members.forEach(studyTeam.displayMembers);`를 보면 forEach로 members 내부 요소를 순회하며 this가 전역 객체를 가리키게 됩니다. 전역 객체엔 displayMembers가 존재하지 않아 “대한민국 소속 짱구 요원”이 출력됩니다.

**Comment by Stilllee** [comment]
자바스크립트에서는 함수의 호출에 따라 `this`의 바인딩 달라집니다.

함수를 함수로서 호출하면 `this`는 전역 객체를 가리키지만, 메서드로서 호출하면 `this`는 상위 객체를 가리킵니다.

콜백 함수는 함수이지만 메서드는 아닙니다. 
따라서 콜백 함수 내부의 `this`는 전역 객체를 가리키는데요, 문제는 특정 객체의 메서드를 콜백 함수로 전달할 때 모양만 보고 `this`가 해당 객체를 가리킬 것이라 착각할 수 있다는 것입니다.

<br>

### studyTeam.displayMembers("짱구");
![image](https://github.com/Coding-Village-Protector/core-js/assets/108785772/2207f8b1-bcdc-4619-9c1d-53703de41d5a)
- 여기서 `studyTeam`의 메서드인 `displayMembers`를 호출했으니 `this`는 당연히 상위 객체인`studyTeam`을 가리킵니다. 

따라서, `this.organization`은 "코딩 마을 방범대"가 됩니다.

<br>

### members.forEach(studyTeam.displayMembers);
![image](https://github.com/Coding-Village-Protector/core-js/assets/108785772/ea607cb7-b2f7-495a-aef5-9cad0dd0d3e7)
- `forEach`함수의 콜백 함수로  `studyTeam`의 메서드인 `displayMembers`를 전달하면, 이 함수는 일반 함수로서 호출되어 `this`가 전역 객체를 가리키게 됩니다.

`studyTeam.displayMembers`만 보고  `studyTeam`의 메서드 `displayMembers`를 호출했으니 `this`는 `studyTeam`을 가리킬 것이라 생각할 수 있지만, 사실은 `studyTeam`의 메서드인 `displayMembers`를 **함수로 전달만**했을 뿐입니다. 

따라서, `this.organization`은 "대한민국"이 됩니다.

<br>
<br>

추가적으로, `forEach`함수의 두 번쨰 인자로 `this`를 지정해주거나, `bind`메서드를 사용하면 `this`를 `studyTeam`으로 고정할 수 있습니다.
```js
members.forEach(studyTeam.displayMembers.bind(studyTeam));
```
![image](https://github.com/Coding-Village-Protector/core-js/assets/108785772/0daf7372-5ce6-408c-a859-859fbab3ebc7)

```js
members.forEach(studyTeam.displayMembers, studyTeam);
```
![image](https://github.com/Coding-Village-Protector/core-js/assets/108785772/a482fe23-a804-439a-832b-4695430d2493)
