### ISSUE TITLE
4.5_콜백 지옥 사용시의 단점과 해결 방안

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/core-js#18]
📝 p107
❓ 다음은 아주 간단한 콜백 지옥의 예시입니다. 다음과 같이 콜백 지옥의 단점과 이를 해결할 수 있는 방안을 답변해주세요.

```js
setTimeout(function (step) {
  console.log(step);
  setTimeout(function (step) {
    console.log(step);
    setTimeout(function (step) {
      console.log(step);
      setTimeout(function (step) {
        console.log(step);
        setTimeout(function (step) {
          console.log(step);
        }, 2000,"step 5");
      }, 2000,"step 4");
    }, 2000,"step 3");
  }, 2000,"step 2");
}, 2000,"step 1");
```

**Comment by Stilllee** [comment]
코드가 길어질수록 들여쓰기가 깊어지고, 실행순서를 아래에서 위로 헤아려야 하기 때문에 가독성이 떨어집니다.

콜백 지옥은 다음과 같은 방법들로 해결할 수 있습니다.
- 기명함수로 전환
- Promise
- Generator
- async/await

<br>

이 중에서 **Promise**를 이용한 해결방안을 설명해보겠습니다.
```js
function delay(step, time) {
  return new Promise(resolve => setTimeout(resolve, time, step));
}

function executeSteps(curStep, totalSteps, time) {
  if (curStep > totalSteps) return;
  
  delay(`step ${curStep}`, time).then(step => {
    console.log(step);
    executeSteps(curStep + 1, totalSteps, time);
  })
}

executeSteps(1, 5, 2000);
```
- **delay**함수 : 
  - 프로미스를 반환합니다. `setTimeout`을 이용해 지정된 시간(`time`)이 지난 후 `resolve`함수를 호출하며, 이때 `resolve`에는 `step`값이 전달됩니다.

-  **executeSteps**함수 :
    - 재귀적으로 자신을 호출합니다. 현재 단계(`curStep`)와 총 단계 수(`totalSteps`), 지연 시간(`time`)을 인자로 받습니다.
    - 각 단계에서 `delay`함수를 호출하고, 프로미스가 이행될 때(`then` 메소드 사용) 로그를 출력한 다음, 다음 단계로 넘어갑니다.
  
<br>

이 방식을 사용하면 각 단계가 순차적으로 실행되며, 콜백 지옥의 복잡성을 피할 수 있고,  `catch`메서드를 통해 에러 처리도 간단히 할 수 있습니다.

<br>

![chrome_2kYt1bajDa](https://github.com/Coding-Village-Protector/core-js/assets/108785772/4e34da42-127e-4dfd-8169-ff11e1e00f0b)

**Comment by eeeyooon** [comment]
콜백 지옥이 발생하면 가독성이 떨어지고 코드를 수정하기도 어려워집니다. 콜백 지옥을 해결하는 가장 간단한 방법은 익명의 콜백 함수를 모두 기명함수로 전환하는 것입니다. 다만 일회성 함수를 전부 변수에 할당하는 것은 비효율적일 수 있습니다. ES6에서는 Promise, Generator를 ES2017에서는 async/await가 도입된 것처럼 더 좋은 방법들이 등장하고 있습니다.

**Comment by chaehaeun** [comment]
콜백 함수를 통한 비동기 처리의 단점으로는
- 중첩된 콜백은 코드의 구조를 복잡하게 만들어 이해하기 어려움
- 에러 처리가 어렵고 예외 처리에 대한 통일성 있는 패턴이 없어 버그가 발생하기 쉬움

등등이 있습니다.

이러한 콜백 지옥을 해결하기 위해 ES6의 promise, ES2017의 aync/await 문법이 등장했습니다.

**Comment by sryung1225** [comment]
**콜백 지옥**은 **콜백 함수를 익명 함수로 전달하는 과정이 반복되면서 코드의 들여쓰기 수준이 감당하기 힘들 정도로 과도하게 깊어지는 현상**을 말합니다.

값을 전달하는 순서가 아래서 위를 향하고 있어 가독성이 저하된다는 단점을 가집니다.

콜백 지옥을 해결하는 가장 간단한 방법은 익명의 콜백 함수를 모두 이름을 가진 선언적 함수로 전환하는 것입니다만 이것은 일회성 함수를 전부 변수에 할당하는 것이 오히려 헷갈릴 소지가 있다는 의견이 있습니다. 때문에 자바스크립트에서 새롭게 도입된 방법이 선호되고 있는데 ES6에서 도입된 **Promise**와 ES2017(ES8)에서 도입된 **async / await**이 있습니다.

**Comment by lulla-by** [comment]
콜백함수는 들여쓰기 수준이 과도하게 깊어지고 전달되는 순서가 아래에서 위를 향하기 때문에 가독성측면과 코드 진행방향이 다소 어색하다는 단점이 있습니다.

이를 해결하기 위한 방안으로 promise와 async/await을 사용할 수 있습니다.
```js
function delayStep(step, time) {
  return new Promise((resolve) => {
    setTimeout(() => {
      console.log(step);
      resolve();
    }, time);
  });
}

```
.then활용
```js
delayStep("step 1", 2000)
  .then(() => delayStep("step 2", 2000))
  .then(() => delayStep("step 3", 2000))
  .then(() => delayStep("step 4", 2000))
  .then(() => delayStep("step 5", 2000));

```
async/await 활용
```js
async function runSteps() {
  await delayStep("step 1", 2000);
  await delayStep("step 2", 2000);
  await delayStep("step 3", 2000);
  await delayStep("step 4", 2000);
  await delayStep("step 5", 2000);
}
```
