### ISSUE TITLE
1.6_"null"과 "undefined" 가 사용되는 상황과 사용 될 때의 의미를 비교해주세요.

### ISSUE THREAD

**Issue by chaehaeun** [Coding-Village-Protector/core-js#2]
📝 p.29
❓  null과 undefined는 모두 값이 "없음" 을 나타내지만 사용되는 상황과 의미에는 약간의 차이가 있는데요. 이 부분에 대해 설명해주세요.

**Comment by Stilllee** [comment]
#### undefined
- 변수가 선언만 되고 값이 할당되지 않았거나, 존재하지 않는 객체 프로퍼티나 함수 반환값에 자동으로 할당됩니다.
- '값이 아직 정의되지 않음'을 의미합니다.

#### null
- 개발자가 명시적으로 '값이 없음'을 표시할 때 사용합니다. 
- 주로 참조해야 할 객체가 없음을 나타낼 때 사용되며, '값이 의도적으로 비어있음'을 의미합니다.

**Comment by eeeyooon** [comment]
둘 다 "없음"을 나타내기 위해 사용됩니다. undefined는 어떤 변수에 값이 존재하지 않을 경우를 의미하고 null은 사용자가 명시적으로 "없음"을 표현하기 위해 대입한 값입니다. undefined는 오직 "값을 대입하지 않은 변수에 접근하고자 할 때 자바스크립트 엔진이 반환해주는 값"으로만 존재하도록 직접 undefined를 할당하지 않을 것을 권장합니다. 
추가로 null은 typeof null이 object이므로, 어떤 변수의 값이 null인지 undefined인지를 판별하기 위해서는 동등 연산자가 아닌 일치 연산자를 써야 정확히 판별할 수 있습니다.

**Comment by lulla-by** [comment]
둘 다 데이터가 존재하지 않음을 위해 사용합니다. 다만 `undefined`는 사용자가 명시적으로 `undefined`라는 값을 할당할 수도 있지만 보통 값이 존재하지 않을 때 자바스크립트 엔진이 자동으로 부여하는 경우가 있습니다. 반면에 `null`은 개발자가 해당 데이터가 비어있음을 의도적으로 표기하기 위해 사용합니다. 

비어있음을 명시적으로 사용하고 싶을 경우에는 `null`을 사용하는 것이 권장됩니다.

**Comment by sryung1225** [comment]
- **undefined** : 사용자가 명시적으로 undefined라는 값을 할당할 수도 있지만 혼란을 방지하기 위해  어떤 변수에 값이 존재하지 않는 경우로 사용합니다.
- **null** : 사용자가 명시적으로 '없음'을 표현하기 위해 대입한 값입니다.

**Comment by chaehaeun** [comment]
undefined의 사용과 의미
- **자동 할당**:변수를 선언했지만 값을 할당하지 않았을 때, 자동으로 undefined가 할당. 변수가 메모리에는 존재하지만, 아직 명확한 값을 갖지 않았음을 나타냄
- **함수 반환값**: 반환값 없이 종료된 함수의 결과는 undefined임. 함수에서 return 문을 생략하면, 자동으로 undefined를 반환.
- **존재하지 않는 속성**: 객체에서 정의되지 않은 속성에 접근하려고 할 때 undefined를 받음. 속성이 객체에 존재하지 않음을 의미.

null의 사용과 의미
- **의도적인 '값 없음'**: null은 개발자가 변수에 '값이 없음'을 명시적으로 할당하기 위해 사용. 이는 변수가 '아무 것도 가리키고 있지 않음'을 의도적으로 나타내고자 할 때 쓰임.
- **객체의 부재를 나타낼 때**: 함수가 객체를 반환할 것으로 예상되지만, 어떤 조건으로 인해 반환할 객체가 없을 때 null을 반환하여 객체의 부재를 나타냄.
