### ISSUE TITLE
5.3.3_클로저를 이용해 쓰로틀링 함수를 작성해주세요.

### ISSUE THREAD

**Issue by chaehaeun** [Coding-Village-Protector/core-js#21]
📝 p138
❓본문에서는 클로저를 사용한 부분 함수 예제로 디바운스를 들었습니다. 디바운스는 프론트엔드 성능 최적화에 큰 도움을 주는 기법 중 하나입니다. 디바운스 외에도 대표적인 이벤트 최적화 기법으로 **쓰로틀링**이 있는데요. 

클로저를 활용해 **1) 쓰로틀링 함수 예시를 작성**하고,  **2) 디바운스와 쓰로틀링을 비교**해 주세요.(작동 방식, 활용 예제 등)

**Comment by Stilllee** [comment]
```

**Comment by Stilllee** [comment]
쓰로틀링은 특정 시간 간격으로 이벤트를 그룹화하며, 이 간격동안 한 번만 이벤트를 발생시키는 기술입니다.

**쓰로틀링 함수 예시**
```js
function throttle(func, limit) {
  let inThrottle;  // 클로저를 통해 추적되는 '쓰로틀링' 상태 변수. 이 변수는 함수가 시간 제한에 의해 쓰로틀링되고 있는지를 추적합니다.

  return function() {
    const args = arguments;  // 클로저를 통해 접근되는 함수의 인자들. 이 인자들은 외부에서 제공됩니다.
    const context = this;  // 클로저를 통해 접근되는 함수의 this 컨텍스트. 이 컨텍스트는 외부 함수의 this 값을 유지합니다.

    if (!inThrottle) {  // 만약 함수가 현재 쓰로틀링 상태가 아니라면,
      func.apply(context, args);  // 외부 함수 func를 현재 컨텍스트와 인자들로 실행합니다.
      inThrottle = true;  // 쓰로틀링 상태를 true로 설정합니다.

      // limit 시간 후에 쓰로틀링 상태를 false로 변경합니다.
      // 이 setTimeout의 콜백 함수 또한 클로저를 형성하여 inThrottle 변수에 접근할 수 있습니다.
      setTimeout(() => inThrottle = false, limit);
    }
  };
}
```
```js
document.body.addEventListener('mousemove', throttle(function() {
  console.log('Mouse moved');
}, 1000));
```
- `throttle` 함수를 문서의 `body`에 `mousemove` 이벤트 리스너를 추가하는 데 사용합니다.
- 마우스가 움직일 때마다 `throttle` 함수를 사용하여 1초 간격으로 'Mouse moved' 로그를 콘솔에 기록합니다.
- 이러한 방식으로, 함수가 매 이벤트마다 실행되는 것이 아니라 지정된 시간 간격으로 실행됩니다.

<br>

**디바운스 vs 쓰로틀링**
- 작동 방식
  - 디바운스 : 연속된 이벤트가 끝나고 정해진 시간이 지나면 한 번만 이벤트를 처리합니다.
  - 쓰로틀링 : 정해진 시간 간격마다 최대 한 번씩 이벤트를 처리합니다.
- 활용 예제
  - 디바운스 : 사용자의 입력을 기다려 자동완성하는 기능에 사용됩니다.
  - 쓰로틀링 : 스크롤 이벤트 처리나 마우스 이동 추적 같은 고빈도 이벤트에 사용됩니다.

**Comment by eeeyooon** [comment]
```js
function throttle(callback, limit = 100) {
  let waiting = false
  return function() {
      if(!waiting) {
          callback.apply(this, arguments)
          waiting = true
          setTimeout(() => {
              waiting = false
          }, limit)
      }
  }
}
```
이 코드에서 클로저는 `waiting`을 기억하고, 이를 통해 함수가 언제 실행 될 수 있는지를 제어합니다.

**디바운스**
- 디바운스는 연속된 이벤트호출들을 그룹화하여 단 하나의 이벤트만 특정 시간이 지난 후에 실행하도록 합니다. 
- 사용자가 input에서 글을 작성할 때 디바운스를 사용하면 사용자가 타이핑을 멈추고 일정 시간이 지나야만 실제 이번트 처리 함수를 호출할 수 있습니다. (타이핑을 멈추고 3초가 지나야 유효성 검사 실시)

**쓰로틀링**
- 쓰로틀링은 이벤트 처리를 일정한 주기에 한 번씩만 실행하도록 합니다.
- 스크롤과 같은 연속적인 이벤트에서 매 주기마다 최대 한번씩만 이벤트 처리 함수가 호출되도록 제한할 수 있습니다.

**Comment by sryung1225** [comment]
시간 관계상... 쓰로틀링 함수를 기존에 프로젝트에서 작성한 코드로 대체합니다. (겸사겸사 타스버전 🫠)
```tsx
const throttle = <T extends any[]>(callback: (...args: T) => void) => {
  let isThrottling = false;
  return (...args: T) => {
    if (isThrottling) return;
    callback(...args);
    isThrottling = true;
    setTimeout(() => {
      isThrottling = false;
    }, 50);
  };
};
```

debounce는 이벤트가 끝날 때까지 기다렸다가 시작됩니다.
throttle은 초당 함수의 실행 횟수를 제한합니다.

**Comment by chaehaeun** [comment]
### 1) 쓰로틀링 함수 예시
```js
function throttle(func, limit) {
  let lastFunc; // 마지막으로 실행된 타이머의 ID를 저장
  let lastRan; // 함수가 마지막으로 실행된 시점
  const innerThrottle = function () {
    const context = this;
    const args = arguments;
    if (!lastRan) {
      //lastRan이 설정되지 않았다면
      func.apply(context, args); // 함수를 즉시 실행하고
      lastRan = Date.now(); // lastRan에 그 시점의 시간을 지정
    } else {
      // lastRan이 설정되어 있다면(함수가 실행된 적 있다면)
      clearTimeout(lastFunc); // 이전에 설정된 타이머가 있다면 타이머를 취소
      lastFunc = setTimeout(function () {
        // 새로운 타이머를 lastFunc에 저장
        if (Date.now() - lastRan >= limit) {
          // 마지막으로 함수가 실행된 시간과 현재 시간의 차이가 limit 이상이면,
          //함수를 실행하고,
          func.apply(context, args);
          // lastRan을 현재 시간으로 업데이트
          lastRan = Date.now();
        }
        // 마지막으로 함수가 실행된 이후로 limit 시간이 지나기 전에는 실행되지 않음
      }, limit - (Date.now() - lastRan));
    }
  };
  return innerThrottle;
}
```
마지막으로 이벤트가 실행된 시점과 현재 시점을 비교하여 설정된 시간 간격 내에서는 이벤트가 빈번히 호출되지 않도록 제어합니다.

### 2) 디바운스와 쓰로틀링 비교
#### 작동방식
- 디바운스 : 이벤트가 발생할 때마다 타이머를 재설정하고, 타이머로 지정해놓은 시간 동안 이벤트가 재발생하지 않으면 마지막 이벤트 함수만 호출합니다.
- 쓰로틀링 : 설정된 시간 간격 동안에는 함수 호출을 한 번만 합니다. 이 시간 간격 내에는 추가적인 함수 호출이 무시하여 이벤트를 일정한 주기로 제한하여 함수 호출 횟수를 조절합니다.

#### 활용 예제
- 디바운스
  - 검색어 추천 기능 : 사용자가 타이핑을 하는 동안 빈번한 api 요청이 들어가지 않게 합니다.
  - 윈도우 리사이징 : 사용자가 윈도우 크기 조정을 멈췄을 때만 레이아웃 계산을 실행하도록 합니다.
- 쓰로틀링
  - 스크롤 이벤트 처리 : 무한 스크롤 웹사이트(스크롤 이벤트로 구현한 경우)에서 스크롤 이벤트가 너무 자주 발생하지 않도록 합니다.
