### ISSUE TITLE
5.3.2_클로저를 이용한 함수 차원의 public/private한 값 구별

### ISSUE THREAD

**Issue by sryung1225** [Coding-Village-Protector/core-js#22]
📝 p129
❓ 자바스크립트는 기본적으로 변수 자체에 public, private, protected와 같은 접근 권한을 직접 부여하도록 설계돼 있지 않습니다. 하지만 클로저를 이용해 함수 차원에서 public한 값과 private한 값을 구분하는 것이 가능합니다.

다음 클로저 예제 코드 속 **변수 `sum`** 에 대해서
위 클로저의 특징에 근거하여 **외부 스코프에서 sum 에 접근이 가능한 지** 여부와 그 이유를 설명해주세요.
```tsx
var counter = function () {
  var sum = 0;
  var increment = function () {
    return sum += 3;
  };
  return increment;
};

var counting = counter();

console.log(counting());
console.log(counting());
```

**Comment by Stilllee** [comment]
`sum`은 `counter`함수 내부에서 선언된 변수로, 이 함수의 외부에서는 접근할 수 없습니다. `increment`함수는 `sum`에 접근하고 수정할 수 있는 클로저를 형성합니다. 따라서, `counter`함수를 호출하면 `increment`함수가 반환되고, 이 함수를 통해 `sum`변수의 값을 변경할 수 있습니다.

즉, `counter`함수를 통해서만 `sum`의 값에 영향을 줄 수 있으며, 직접 접근할 수는 없습니다.

**Comment by chaehaeun** [comment]
`sum` 변수에 직접적으로 접근할 수 없습니다.

`sum`은  counter 함수에 의해 생성된 클로저 내에 포함되어 있는 로컬 변수이므로 private 변수로 동작하고,  `sum`을 참조하는 내부 함수 `increment` 를 통해서만 간접적으로 접근하고 수정할 수 있습니다.

**Comment by eeeyooon** [comment]
직접적으로 `sum`을 접근할 수는 없으나 `increment` 함수는 sum을 참조할 수 있는 내부 함수로 클로저를 형성하였기 때문에, `increment`를 통해서 `sum`의 값에 간접적으로 접근할 수 있습니다.

**Comment by sryung1225** [comment]
외부 스코프에서 `sum` 에 접근 가능합니다. 

정확히 말하자면 직접 접근할 수는 없으나 **`counter()`에서 반환한 `increment()` 를 통해 `sum` 에 간접적으로 영향을 줄 수 있게 됩니다.**

예제 속 `counter()` 는 외부(전역 스코프)로부터 철저하게 격리된 공간입니다. 외부에서는 외부 공간에 노출돼 있는 `counting` 라는 변수를 통해 `counter()` 를 실행할 수 있지만 `counter()` 내부에는 어떠한 개입도 할 수 없습니다. **오로지 `counter()` 가 return한 정보에만 접근 가능하게 됩니다.**

```tsx
var counter = function () {
	var sum = 0; // <--- increment() 를 통해 외부에서 접근 가능해진 counter의 지역 변수 sum
	var increment = function () {
		return sum += 3;
	};
	return increment; // <--- counter() 외부에서도 increment() 접근 가능하게 만듬
};

var counting = counter(); 

console.log(counting()); // ? 3
console.log(counting()); // ? 6
```

예제에서는 `counter()` 가 종료할 때 `increment()` 를 return 해주었습니다. 이 영향으로 `counter()` 의 외부에서도 `counter()` 내부의 변수(지역변수)인 `sum` 을 읽을 수 있게 됩니다. 때문에 출력 결과가 차례로 3, 6이 됩니다.

정리하자면 클로저는 `return` 을 이용해 함수 내부의 변수들 중 일부 변수에 대한 접근 권한을 외부 스코프에 부여할 수 있습니다. 이렇게 반환된 변수들은 공개 멤버(public member)가 되고, 그 외의 변수들은 비공개 멤버(private member)인 셈입니다. 

위 예제에서는 `sum` 은 함수 `increment()` 의 한해 공개 멤버입니다.
