### ISSUE TITLE
5.3.4_커링 함수란 무엇이고 커링 함수가 유용한 상황은 언제일까요?

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/core-js#24]
📝 141p
❓ 커링 함수란 무엇이고 커링 함수가 유용한 상황은 언제일까요? 
그리고 아래에 제시되는 코드를 커링 함수로 바꿔보거나 혹은 다른 예제 코드를 제시하여 커링 함수로 바꿔주세요.

```js
function sum(x,y) {
	return x+y;
}
```

**Comment by chaehaeun** [comment]
### 커링 함수란
여러 개의 인자를 받는 함수를 하나의 인자만 받는 함수로 나눠서 순차적으로 호출될 수 있게 체인 형태로 구성한 것을 말합니다.

### 커링함수가 유용한 상황
1. 부분 적용 : 함수의 일부 인자를 미리 채워넣고 나머지 인자를 나중에 처리하고 싶은 경우
2. 지연 실행 : 원하는 시점까지 지연 시켰다가 마지막 인자가 넘어가면 함수 실행을 시키고 싶은 경우

### 질문 예제를 커링 함수로 바꾸었을 때
```js
const sum = x => y => x + y;
```

**Comment by Stilllee** [comment]
**커링함수**는 매개변수의 부분 적용을 가능하는 프로그래밍 패턴입니다. 각각의 매개변수를 하나씩 받아 마지막 매개변수가 전달될 때까지 함수의 실행을 지연시키고, 모든 매개변수가 주어졌을 때 비로소 원래의 함수 실행을 완료합니다. 이런 방식은 코드의 재사용을 높이고, 모듈화를 강화하는 데 유용합니다.

커링 함수는 다음과 같은 상황에서 유용합니다
1. **재사용성 향상** : 공통 매개변수를 가진 여러 함수를 생성할 때 유용
2. **함수 조합과 파이프라인** : 커링을 이용해 데이터를 순차적으로 처리하는 함수 파이프라인 구성 가능
3. **지연 실행** : 필요한 모든 매개변수가 모일 때까지 함수 실행을 지연시킬 수 있어 실행 시점 조절이 가능

```js
fcuntion sum(x) {
  return function(y) {
    return x + y;
  };
}
```
```js
// ES6의 화살표 함수
const sum = x => y => x + y;
```

**Comment by sryung1225** [comment]
커링 함수란 여러 개의 인자를 받는 함수를 하나의 인자만 받는 함수로 나눠서 순차적으로 호출될 수 있게 체인 형태로 구성한 것을 말합니다. 한 번에 하나의 인자만 전달하는 것을 원칙으로 합니다. 

커링 함수는 부분 적용 함수와 비교해 필요한 상황에 직접 만들어 사용하기에 유용합니다. 그리고 프로젝트 상황에서 자주 쓰이는 함수의 매개변수가 항상 비슷하고 일부만 바뀌는 경우에도 유용하게 사용할 수 있습니다.

예제 코드를 커링 함수로 변환하면 다음과 같이 작성할 수 있습니다.

```tsx
function sum(x) {
  return function(y) {
    return x + y;
  };
}
```

**Comment by eeeyooon** [comment]
커링 함수란 여러 개의 인자를 받는 함수를 하나의 인자만 받는 함수로 나눠서 순차적으로 호출될 수 있게 체인 형태로 구성한 것을 말합니다. 당장 필요한 정보만 받아서 전달하고 또 필요한 정보가 들어오면 전달하는 식으로 진행되기 때문에 마지막 인자가 넘어갈 때까지 함수 실행을 미루는, "지연실행"이 가능합니다. 원하는 시점까지 지연시켰다가 실행해야 하는 상황이라면 커링을 쓰기에 적합한 상황입니다.


```js
function sum(x) {
	return function(y) {
		return x + y;
	};
}
```

```js
function sum(a) {
	return (b) => {
		return a+b;
	}
};
const add2 = sum(2);
const five = add2(3); 
console.log(five); // 5
```

다양한 방식으로 커링 함수 변환을 할 수 있습니다.
