### ISSUE TITLE
6.2.3_객체 전용 메서드들을 Object에 스태틱 메서드로 부여할 수 밖에 없었던 이유에 대해 설명해주세요.

### ISSUE THREAD

**Issue by chaehaeun** [Coding-Village-Protector/core-js#25]
📝 p169
❓ 객체 전용 메서드들을 Object.prototype이 아닌 Object에 스태틱 메서드로 부여할 수 밖에 없었던 이유에 대해 설명해주세요.

**Comment by sryung1225** [comment]
어떤 메서드를 호출하면 자바스크립트 엔진은 데이터 자신의 프로퍼티들을 검색해서 원하는 메서드가 있으면 그 메서드를 실행하고, 없으면 `__proto__` 프로퍼티를 검색해 연쇄적으로 따라가는 프로토타입 체이닝을 하는데, 이때 어떤 생성자 함수이든 최종적으로 `Object.prototype`이 프로토타입 체인의 가장 최상단에 존재하게 됩니다.
이 말인즉슨 어떤 데이터 타입도 `Object.prototype` 내부에 정의된 메서드를 사용할 수 있다는 의미가 됩니다.
따라서 객체만을 대상으로 동작하는 객체 전용 메서드들은 Object의 스태틱 메서드로 부여해야만 합니다.

**Comment by eeeyooon** [comment]
객체 한정 메서드들을 `Object.prototype`이 아닌 `Object`에 직접 부여할 수밖에 없었던 이유는 `Object.prototype`이 여타의 참조형 데이터뿐 아니라 기본형 데이터조차 `__proto__`에 반복 접근함으로써 도달할 수 있는 최상위 존재이기 때문입니다.
객체에서만 사용할 메서드를 `Object.prototype` 내부에 정의한다면 다른 데이터 타입도 해당 메서드를 사용할 수 있기 때문에 객체만을 대상으로 동작하는 객체 전용 메서드들은 `Obejct`에 스태틱 메서드로 부여할 수 밖에 없었습니다.

**Comment by lulla-by** [comment]
어떤 생성자 함수이든 prototype은 반드시 객체이기 때문에 프로토타입 체인 최상단에는 `Object.prototype`이 존재합니다. 따라서 객체에서만 사용하는 메서드를 프로토타입 객체 안에 정의하게 되면 다른 데이터 타입도 해당 메서드를 사용할 수 있어 예상치 못한 오류가 발생할 수 있습니다.

**Comment by Stilllee** [comment]
자바스크립트의 모든 객체는 프로토타입 체인을 통해 `Object.prototype`에 연결되어 있습니다. 이는 `Object.prototype`이 모든 객체의 최상위 프로토타입으로 존재한다는 것을 의미합니다. 따라서, `Object.prototype`에 추가된 메서드는 모든 객체가 접근할 수 있는 범용적인 메서드가 됩니다. 

그러나, `Object.prototype`에 메서드를 추가하는 것은 예상치 못한 부작용을 초래할 수 있기 때문에 객체 전용 메서드들은 `Object.prototype`이 아닌 `Object`에 스태틱 메서드로 정의됩니다.

**Comment by chaehaeun** [comment]
Object.prototype에 메서드를 추가하면 JavaScript에서 생성된 모든 객체가 해당 메서드를 상속받게 됩니다. 이것은 필요하지 않은 메모리 사용을 야기할 수 있고, 모든 객체에 불필요한 메서드를 추가할 위험이 있습니다. 그렇기 때문에 '객체 자체'에 대한 일반적인 작업을 수행하기 위해 스태틱 메서드로 부여할 수 밖에 없었습니다.
