### ISSUE TITLE
6.1.1_MDN 문서에서 나열된 Array 객체의 메서드간의 차이점 알아보기

### ISSUE THREAD

**Issue by sryung1225** [Coding-Village-Protector/core-js#26]
📝 p155
❓ 다음 아래 이미지는 MDN의 JavaScript 참고서 중 `Array`에 해당되는 내용의 카테고리 일부를 캡쳐한 것입니다. (https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array)

![image](https://github.com/Coding-Village-Protector/core-js/assets/26590099/2ae2746e-004a-424c-bffb-aa8ebfdf7dcd)

보다시피 `Array`의 메서드들이 차례로 나열되어 있는데 `Array.isArray()`와 `Array.of()`는 다른 메서드들과 생김새가 조금 다른듯합니다. 두 메서드와 다른 메서드의 차이는 무엇인지 각각을 일컫는 단어와 함께 설명해주세요. 
(필요시 콘솔 출력 결과 혹은 도식화를 통한 비교 가능합니다.)

**Comment by eeeyooon** [comment]
`new` 연산자와 함께 함수를 호출할 경우, 그로부터 생성된 인스턴스에는 숨겨진 프로퍼티인 `__proto__`가 자동으로 생성되며, 이 프로퍼티는 생성자 함수의 prototype 프로퍼티를 참조합니다. `__proto__` 프로퍼티는 생략 가능하도록 구현돼 있기 때문에 생성자 함수의 `prototype`에 어떤 메서드나 프로퍼티가 있다면 인스턴스에서도 마치 자신의 것처럼 해당 메서드나 프로퍼티에 접근할 수 있습니다. 
여기서 `map`, `pop`, `push`와 같은 메서드들은 `Array`의 프로토타입 체인을 통해 배열 인스턴스에 상속되어 배열 인스턴스에서 직접 호출할 수 있는 인스턴스 메서드입니다. 
하지만 `of`, `isArray`는 `Array` 생성자 함수 자체에 직접 정의된 스태틱 메서드입니다.  `Array`의 `prototype` 프로퍼티 내부에 있지 않기 때문에 인스턴스가 직접 호출할 수 없습니다. 이들은 `Array` 생성자 함수에서 직접 접근해야 실행이 가능합니다.

**Comment by lulla-by** [comment]
`Array.isArray()`와 `Array.of()`는 **스태틱메서드**이며 그 외에 `Array.prototype` 내부에 연결된 메서드는 **인스턴스 메서드**입니다. 두 메서드의 차이를 설명하면 스태틱 메서드는 생성자 함수 그 자체에 부여된 메서드로 인스턴스 없이 생성자 함수의 이름을 통해 바로 호출됩니다.
```js
function Circle(radius) {
  this.radius = radius;
}

// 인스턴스 메서드
Circle.prototype.calculateArea = function() {
  return Math.PI * this.radius * this.radius;
};

const circle1 = new Circle(5);

// __proto__로 Circle.prototype에 접근하여 calculateArea() 호출
console.log(circle1.calculateArea());
```
  반면, 인스턴스메서드는 `prototype` 객체내부에 설정된 메서드로 생성자 함수로 생성된 인스턴스가  `__proto__`를 이용한 프로토타입 체이닝을 통해 호출이 가능합니다.

```js
function Circle(radius) {
  this.radius = radius;
}

// 정적 메서드
Circle.createDefault = function() {
  return new Circle(1);
};

// 직접 호출
const defaultCircle = Circle.createDefault()
```
또한, createDefault는 생성자 함수 자체에 정의된 스태틱 메서드로 다음과 같이 프로토타입에 접근하여 호출할 수 없습니다
![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/55092a83-fe43-43d2-866d-427b3e15533d)

**Comment by lulla-by** [comment]
`Array.isArray()`와 `Array.of()`는 **스태틱메서드**이며 그 외에 `Array.prototype` 내부에 연결된 메서드는 **프로토타입 메서드**입니다.

프로토타입 메서드의 생성 방식은 다음과 같습니다. 생성자 함수의 prototype 내부에 메서드를 생성하여 프로토타입 메서드를 생성할 수 있습니다.  `new`연산자와 생성자 함수를 통해 생성된 인스턴스는  __proto__를 통해 해당 메서드에 접근 가능합니다.

```js
function Circle(radius) {
  this.radius = radius;
}

// 프로토타입 메서드
Circle.prototype.calculateArea = function() {
  return Math.PI * this.radius * this.radius;
};

const circle1 = new Circle(5);

// __proto__로 Circle.prototype에 접근하여 calculateArea() 호출
console.log(circle1.calculateArea());
```

반면, prototype을 사용하지않고 생성자함수에 바로 메서드를 생성하면 해당 메서드는 스태틱 메서드가 됩니다. 이러한 메서드는 프로토타입메서드와 다르게 __proto__를 통한 접근이 불가능합니다. 생성자 함수에서 바로 접근해야 호출이 가능합니다. 문제의 `Array.isArray()`와 `Array.of()`가 바로 스태틱 메서드입니다.


다음은 정적메서드의 생성 방식입니다.
```js
function Circle(radius) {
  this.radius = radius;
}

// 정적 메서드
Circle.createDefault = function() {
  return new Circle(1);
};

// 직접 호출
const defaultCircle = Circle.createDefault()
```

**Comment by chaehaeun** [comment]
Array.isArray()와 Array.of()는 정적 메서드로, Array의 프로토타입 체인과는 별도로 Array 함수 객체에 직접 부여된 메서드입니다.
반면, 대부분의 Array 메서드들은 인스턴스 메서드로서, Array의 프로토타입 객체에 정의되어 있습니다. 

### 스태틱 메서드
- 클래스 또는 생성자 자체에 바인딩되어 있는 메서드로, 인스턴스를 생성하지 않고도 직접 호출할 수 있습니다.
- `Array.isArray()`와 `Array.of()`는 `Array`의 인스턴스가 아닌, `Array` 자체에 대한 작업을 수행합니다.

### 인스턴스 메서드
- 인스턴스 메서드는 인스턴스에 바인딩되어 있는 메서드로, 해당 클래스의 객체(인스턴스)를 통해서만 호출할 수 있습니다.
- `.push()`, .`pop()`, .`map()` 같은 인스턴스 메서드들은 `Array` 인스턴스에 적용되며, 인스턴스의 데이터를 조작합니다.

**Comment by Stilllee** [comment]
`Array.isArray()`와 `Array.of()`는 다른 메서드들과 달리 `Array.prototype`을 통해 정의되지 않고, `Array`객체에 직접 정의된 스태틱 메서드입니다.

스태틱 메서드는 특정 배열 인스턴스에 바인딩되지 않고, 배열 생성자 자체에 연결되어 있어, 인스턴스를 생성하지 않고도 직접 호출할 수 있습니다.

반면, `Array.prototype`에 정의된 나머지 메서드들은 배열 인스턴스에 종속되어 인스턴스를 통해서만 호출할 수 있는 인스턴스 메서드 입니다.  이 메서드들은 배열 인스턴스의 프로토타입 체인을 통해 상속되므로, 모든 배열 인스턴스에 자동으로 사용할 수 있는 메서드가 됩니다.

**Comment by sryung1225** [comment]
**정적 메서드 (static method)**

문제의 `Array.isArray()` `Array.of()` 는 `Array` 생성자 함수에 정의된 정적 메서드입니다. 생성자 함수에 직접 정의된 메서드를 말하며, 인스턴스를 생성하지 않고 해당 함수의 이름으로 직접 호출할 수 있습니다. `Array` 인스턴스가 아닌 `Array` 생성자 함수 자체에 바인딩되어 있기 때문에 `Array.isArray(값)` 같은 형태로 직접 호출 가능합니다.

<br />

**프로토타입 메서드 (prototype method)**

문제의 `Array.prototype.~~~()` 들은 `Array` 생성자 함수의 prototype에 정의된 프로토타입 메서드입니다. 이 메서드들은 생성된 인스턴스를 통해 사용 가능하며 `__proto__` 속성을 통해 접근 가능합니다. 즉, 모든 생성자 함수의 인스턴스가 사용할 수 있습니다. `let arr = [1,2,3]` 과 같이 배열 인스턴스를 생성하고나서 `arr.push(1)` 과 같은 형태로 호출 가능합니다.

(+ MDN 에서는 static과 instance로 구분해 정의했기에 이전에 준비한 답변은 인스턴스 메서드였으나 책 7장을 참고하여 프로토타입 메서드로 답변을 정리합니다. 완전히 틀린 답이 아님을 기록해둡니다.)

![image](https://github.com/Coding-Village-Protector/core-js/assets/26590099/38778237-4e7a-4519-922d-b6c6365affd7)

<hr />

책에서 주어줬던 예시를 출력결과와 함께 다시 한 번 비교해보겠습니다.

```tsx
var arr = [1, 2];
console.dir(arr);   // ? Array(2)
console.dir(Array); // ? Array()
```

![image](https://github.com/Coding-Village-Protector/core-js/assets/26590099/f71085d1-e1e4-4e7a-8202-ef85b7f43038)

변수 `arr` 을 출력한 결과 `[[Prototype]]` 을 통해 프로토타입 메서드들을 볼 수 있습니다.

![image](https://github.com/Coding-Village-Protector/core-js/assets/26590099/75e97099-c821-483b-8366-9878f7a1d5ab)

생성자 함수 `Array` 를 출력한 결과 정적 메서드들이 우선 나열되고, `prototype` 을 통해 인스턴스 메서드들을 볼 수 있습니다.

위 예시에서 `[1, 2]` 는 instance입니다. 이 instance는 `Array` 의 프로토타입 메서드인 `map` `pop` `push` 등을 얼마든지 사용할 수 있습니다. 하지만 정적 메서드인 `isArray` `of` 등은 직접 사용할 수 없다는 차이를 가집니다.

```tsx
arr.isArray();      // 🚨 TypeError: arr.isArray is not a function
Array.isArray(arr); // true
```
