### ISSUE TITLE
6.2.1_인스턴스 메서드와 프로토타입 메서드의 동작 차이

### ISSUE THREAD

**Issue by Stilllee** [Coding-Village-Protector/core-js#28]
📝 p160
❓ 다음 코드를 보고 출력되는 결과와 그 이유를 설명해주세요. 
(코드 실행 과정에서 발생하는 **어떤 현상**과 관련지어 설명해주세요)
```js
function Animal(name) {
  this.name = name;
}

Animal.prototype.speak = function () {
  return `저는 ${this.name}`;
};

var dog = new Animal("바둑이");
dog.speak = function () {
  return `멍멍! 저는 ${this.name}`;
};

console.log(dog.speak());  // 출력 결과 (A)
console.log(dog.__proto__.speak.call(dog));  // 출력 결과 (B)
```

**Comment by chaehaeun** [comment]
출력 결과 (A): 멍멍! 저는 바둑이
이유: `dog` 객체에 직접 메서드 `speak`를 메서드 오버라이딩했기 때문에, 이 메서드가 우선적으로 호출됩니다. 객체 자체의 메서드가 우선순위를 가지기 때문입니다.

출력 결과 (B): 저는 바둑이
이유: `dog.__proto__`는 `Animal.prototype`을 가리킵니다. 그리고 `call` 메서드를 사용하여 `speak` 메서드를 `dog` 객체의 컨텍스트에서 실행합니다. 따라서 프로토타입 체인을 통해 `Animal.prototype.speak` 메서드가 호출되고, 이 메서드 내부의 `this`는 `dog `객체를 가리키게 됩니다.

**Comment by lulla-by** [comment]
각각의 출력 결과는 다음과 같습니다.
![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/f4333b20-5869-41f9-b0ff-409fc4bd50f6)

이렇게 되는 이유는 **1) this가 무엇을 가리키는지**에 따라 다르고 **2)같은 이름의 speak 메서드여도 스태틱 메서드인지 프로토타입메서드인지로 서로 구분**되기 때문입니다. 먼저 함수가 메서드로 호출될 시에 this는 함수를 호출한 객체가 됩니다. 여기서는 각각 `dog`와 `dog.__proto__`가 됩니다. 

```js
function Animal(name) {
  this.name = name;
}

var dog = new Animal("바둑이");
```

이 코드에서 this.name은 dog에 바로 생성됩니다. 그렇기 때문에`dog.__proto__ `에 접근하면 

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/8c783553-2627-463e-b8bf-f695f146955c)

이런 결과가 나올것입니다. 

왜냐하면 `dog.__proto__`가 `this`인데  `dog.__proto__`에는 `name` 프로퍼티가 없으니까요.

따라서 이 문제를 해결해주기위해 `call`을 사용하여 `this`를 `dog`로 설정해준것입니다. 이렇게되면 `dog.__proto__`는 `dog`를 가리키게 되어 다음과 같이 정상적으로 출력이 됩니다.

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/47aa37ac-8216-4782-8d1d-b65014c509e3)


또한 다음의 두 코드는 speak가 설정된 위치에 따라 스태틱메서드와 프로토타입메서드로 나뉩니다.
```js 
// 프로토타입 메서드(인스턴스 메서드)
Animal.prototype.speak = function () {
  return `저는 ${this.name}`;
};
```

```js
// 스태틱 메서드
dog.speak = function () {
  return `멍멍! 저는 ${this.name}`;
};
```
그렇기 때문에 각각 호출 결과가 다르게 나옵니다.

**Comment by lulla-by** [comment]
출력 결과
(A): 멍멍! 저는 바둑이
(B): 저는 바둑이

A의 경우 `dog`라는 객체 자체에 `speak`라는 메서드를 부여했다. 프로토타입 체이닝은 먼저 자신의 프로퍼티를 검색하여 해당 메서드가 있는지 확인하고 없으면 `__proto__`를 검색하는 순서로 진행된다. 여기에서는 `speak`가 `dog`의 프로퍼티로 존재하여 `멍멍! 저는 바둑이`가 호출된 것이다.

B는 `__proto__`를 타고가서 `dog`자체에 부여된 스태틱 메서드가 아닌 인스턴스 메서드를 호출했다. 다만, 여기서는 메서드 호출방식으로 `this`가 `dog.__proto__`로 설정되어 `name` 프로퍼티를 찾을 수 없다. 따라서 `call`을 사용하여 `this`를 `dog`로 설정한것이다.

메서드 오버라이딩을 사용한 예시로 메서드 오버라이딩은 **교체**가 아니라 **얹는** 개념이기에 위와 같이 `dog`객체에 같은 이름의 메서드를 설정하더라도 `__proto__`를 통해 `prototype`에 접근이 가능하다.

**Comment by sryung1225** [comment]
예제는 인스턴스가 동일한 이름의 메서드를 갖고 있는 경우에 해당합니다.

**(A) 멍멍! 저는 바둑이**

메서드 위에 메서드를 덮어씌우는 **메서드 오버라이드**가 발생하여 `dog` 객체에 직접 정의된 `speak` 메서드가 호출됩니다. 자바스크립트 엔진은 `speak` 라는 메서드를 찾을 때 가장 가까운 대상인 자신의 프로퍼티부터 검색한 뒤 `__proto__` 에 있는 메서드를 검색하기 때문에 `dog.speak` 가 우선 검색됩니다. 그리고 `this.name` 이 `dog` 객체의 `name` 프로퍼티를 참조하기 때문에 최종적으로 “멍멍! 저는 바둑이” 가 출력됩니다.

**(B) 저는 바둑이**

원본 메서드인 `dog.__proto__.speak` 가 호출됩니다. 이 때 사용된 `call` 메서드는 첫 번째 인자로 주어지는 객체를 `this` 로 하여 함수를 호출하기 때문에 문제에서는 `dog` 객체의 `name` 프로퍼티를 참조하게 만듭니다. 최종적으로 “저는 바둑이”가 출력됩니다.

**Comment by eeeyooon** [comment]
**출력 결과**
(A): 멍멍! 저는 바둑이
(B): 저는 바둑이

(A) - 메서드 오버라이드가 발생하여 `dog` 객체 자체에 `speak` 메서드를 정의하였습니다. 그래서 `speak`메서드가 우선 호출됩니다.
(B) - `dog.__proto__.speak`가 호출됩니다. `call` 메서드를 사용하여 `this`를 `dog`로 설정하였습니다.

**Comment by Stilllee** [comment]
이 코드의 핵심은 **메서드 오버라이딩**입니다.

#### 메서드 오버라이딩
메서드 오버라이딩은 상위 클래스 또는 프로토타입의 메서드를 하위 클래스 또는 인스턴스가 재정의하는 현상을 말합니다.

여기에서는 `dog`인스턴스에서 `Animal.prototype.speak`메서드를 새롭게 정의함으로써 발생합니다. 

```js
Animal.prototype.speak = function () {
  return `저는 ${this.name}`;
};

var dog = new Animal("바둑이");
dog.speak = function () {
  return `멍멍! 저는 ${this.name}`;
};
```
- `Animal`의 `speak`메서드는 모든 `Animal`인스턴스들이 사용할 수있는 기본적인 기능을 제공하지만, `dog`인스턴스는 이를 `"멍멍! 저는 바둑이"`이라는 특정 문자열을 반환하는 자체 메서드로 재정의합니다.

핵심은 같은 이름의 메서드가 존재하더라도, 인스턴스별로 서로 다른 기능을 수행한다는 것입니다.

<br>

#### 출력 결과
```js
console.log(dog.speak());  // 멍멍! 저는 바둑이
```
- `dog`인스턴스에 정의된 `speak`메서드를 호출합니다.
- 이 메서드는 "멍멍! 저는 바둑이"라는 문자열을 반환합니다.

```js
console.log(dog.__proto__.speak.call(dog));  // 저는 바둑이
```
- `Animal`프로토타입의 원본 `speak`메서드를 `dog`인스턴스의 컨텍스트에서 호출합니다.
- 이 경우 "저는 바둑이"라는 문자열이 반환됩니다.
