### ISSUE TITLE
6.1.1_프로토타입 체인의 관점에서 `prototype` 프로퍼티와 `__proto__` 프로퍼티의 차이에 대해 설명해주세요.

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/core-js#29]
📝 148p
❓ 프로토타입 체인의 관점에서 `prototype` 프로퍼티와 `__proto__` 프로퍼티의 차이에 대해 설명해주세요.

**Comment by lulla-by** [comment]
`prototype`과 `__proto__` 는 프로토타입 개념의 핵심으로 모두 객체입니다.

`prototype`객체는 생성자 함수에 속한 프로퍼티로 해당 객체 내부에 메서드를 생성하면 해당 메서드는 프로토타입 메서드가 됩니다. 

이때 생성자 함수를 사용하여 만든 인스턴스는 마치 자신의 것처럼 생성자함수의 `prototype`객체 내부의 메서드 즉 프로토타입 메서드를 호출할 수 있습니다. 

여기서 인스턴스는 `__proto__`라는 숨겨진 객체를 가지고 있는데 이 `__proto__`가 생성자함수의 `prototype`객체를 참조하여 접근이 가능합니다.

**Comment by Stilllee** [comment]
`prototype`은 특정 함수가 생성자로 사용될 때 그 함수에 의해 만들어진 모든 객체들이 공유하는 템플릿이라고 볼 수 있습니다. 

반면, `__proto__`는 어떤 객체든 갖고 있는 내부 프로퍼티로, 그 객체가 실제로 상속받은 프로토타입(즉, 메서드와 속성의 원천)을 가리킵니다.

**Comment by chaehaeun** [comment]
- `prototype`은 함수 객체에만 있는 프로퍼티로, 생성자 함수로부터 생성된 객체들이 상속받을 프로토타입을 정의합니다.
- `__proto__`는 모든 객체에 있는 프로퍼티로, 그 객체가 실제로 상속받고 있는 프로토타입 객체를 가리킵니다.
- 기본적으로 객체의 `__proto__`는 해당 객체를 생성한 생성자 함수의 `prototype` 프로퍼티를 참조합니다.

**Comment by sryung1225** [comment]
`prototype` 프로퍼티는 함수가 생성자로 사용될 때 해당 함수로부터 생성된 객체들이 상속받을 프로토타입을 가리킵니다. 
반면 `__proto__` 프로퍼티는 객체가 실제로 상속받고 있는 프로토타입을 가리키는 내부 프로퍼티입니다. 
`prototype` 객체 내부에는 인스턴스가 사용할 메서드를 저장하고, 인스턴스에서도 숨겨진 프로퍼티인 `__proto__`를 통해 이 메서드들에 접근할 수 있게 됩니다.

**Comment by eeeyooon** [comment]
프로토타입 체인에서 `prototype` 프로퍼티는 함수 객체가 생성자로 사용될 때, 이 함수로 생성된 모든 인스턴스가 공유할 프로토타입 객체를 가리킵니다. 반면 모든 객체가 가지고 있는 `__proto__` 프로퍼티는 그 객체가 실제로 상속받고 있는 프로토타입, 즉 부모 객체를 참조합니다. 따라서 `prototype`은 생성자 함수에만 존재하는 프로퍼티이며, `__proto__`는 모든 객체에 존재하여 해당 객체의 프로토타입 체인을 형성하는 링크 역할을 합니다. 주의할 점은 `__proto__`는 비표준이며, 최신 자바스크립트 환경에서는 `Object.getPrototypeOf()` 또는 `Object.setPrototypeOf()` 메서드를 사용하는 것이 권장됩니다.
