### ISSUE TITLE
1.1.2_변수와 식별자의 차이는 무엇인가요?

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/core-js#3]
📝 4p
❓ 변수와 식별자의 차이는 무엇인가요?

보통 변수와 식별자를 혼용하는 경우가 많습니다. 식별자라라고 해야 할 곳에 변수를, 변수라고 해야 할 곳에 식별자를 쓰는 식으로 말이죠. 혼용이 가능한 이유는 대부분의 경우에 문맥에 따라 무엇을 말하고자 하는지를 유추할 수 있기 때문이지만 둘의 차이를 모른다면 혼란스러울 수 있습니다.

이때, 변수와 식별자의 차이는 무엇일까요?

**Comment by Stilllee** [comment]
#### 변수 : 
변할 수 있는 데이터를 뜻합니다.

#### 식별자 : 
어떤 데이터를 식별하는데 사용하는 이름, 즉 변수명을 뜻합니다.

**Comment by lulla-by** [comment]
변수: 변수는 '변할 수 있는 수'이지만 컴퓨터 용어로는 '변할 수 있는 무언가'를 뜻합니다. 여기서 무언가는 데이터를 뜻하며 결국 숫자, 문자열, 객체 , 배열 등 **변할 수 있는 데이터**를 말합니다.

식별자: 식별자는 어떠한 데이터를 식별하는 사용하는 이름으로, 즉 **변수명**을 뜻합니다.

**Comment by chaehaeun** [comment]
변수 : 숫자, 문자열, 객체, 배열 등 변경 가능한 데이터가 담길 수 있는 공간을 뜻합니다.
식별자 : 데이터를 구분하기 위해 이용되는 이름을 말합니다. 변수의 경우 변수명에 해당합니다.

**Comment by eeeyooon** [comment]
<html>
<body>
<p>변수는 “변할 수 있는 수”입니다. 여기서 수는 숫자를 의미하기도 하지만, 값이 반드시 숫자여야 하는 것은 아닙니다. 컴퓨터 용어로 쓸 때는 “변할 수 있는 무언가”라는 명사로 확장시켰습니다. 여기서 무언가는 데이터를 말합니다. 식별자는 어떤 데이터를 식별하는 데 사용하는 이름, 즉 변수명입니다.</p>
<p>자세히 말하자면, 변수는 어떤 값을 저장하기 위한 메모리 공간이나 그 공간을 식별하기 위한 이름을 의미합니다. 식별자는 변수나 함수, 클래스 이름과 같이 메모리 상의 어떤 값을 구별하여 식별할 수 있는 고유한 이름을 의미합니다. 식별자는 특정 값이 아닌 그 값이 존재하는 메모리 주소를 기억하고 있습니다. 자바스크립트에서 식별자는 문자, 숫자, 언더스코어, 달러 기호로 사용할 수 있습니다.</p>
<pre><code class="language-tsx">var a;
</code></pre>

주소 | 1002 | 1003
-- | -- | --
데이터 |   | 이름 : a
값 : |   |  


<p>위와 같이 변수를 할당하면 컴퓨터는 메모리에서 비어있는 공간 하나를 확보합니다. 임의로 그 공간을 1003번으로 지정했을 때, 이 공간의 이름이자 식별자가 “a”가 됩니다. 여기까지가 변수 선언 과정입니다. 이후 사용자가 a에 접근하고자 하면 컴퓨터는 메모리에서 a 라는 이름을 가진 주소를 검색해 해당 공간에 담긴 데이터를 반환할 것입니다.</p>

</body>
</html>

**Comment by sryung1225** [comment]
변수(variable) 는 변할 수 있는 데이터를 말하고, 식별자(identifer) 는 어떤 데이터를 식별하는 데 사용하는 이름, 즉 변수명을 말합니다.
