### ISSUE TITLE
7.2_`스태틱 메서드`와  `프로토타입 메서드`의 차이점을 설명해주세요.

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/core-js#31]
📝 p178
❓ `스태틱 메서드`와  `프로토타입 메서드`의 차이점을 설명해주세요.

**Comment by eeeyooon** [comment]
```js
01  var Rectangle = function(width, height) {
02   this.width = width;
03   this.height = height;
04  };
05  Rectangle.prototype.getArea = function() {
06   return this.width * this.height;
07  };
08  Rectangle.isRectangle = function(instance) {
09   return (
10     instance instanceof Rectangle && instance.width > 0 && instance.height > 0
  );
11 };

12 var rect1 = new Rectangle(3, 4);
13 console.log(rect1.getArea()); // 12 (O)
14 console.log(rect1.isRectangle(rect1)); // Error (X)
15 console.log(Rectangle.isRectangle(rect1)); // true
```
예제 코드를 보면 `Rectangle` 함수를 `new` 연산자와 함께 호출해서 생성된 인스턴스를 `rect1`에 할당하였습니다. 또한 `getArea` 메서드와 `isRectangle` 메서드를 생성하였습니다.

`rect1.getArea()`와 같이 호출된 `getArea`는 실제로는 `rect1.__proto__.getArea`에 접근하며 결과로는 `rect1.width * rect1.height`의 계산값이 반환됩니다. 이처럼 인스턴스(`rect1`)에서 직접 호출할 수 있는 메서드(`getArea`)가 바로 **프로토타입 메서드**입니다.

하지만 `rect1` 인스턴스에서 `isRectangle`메서드로 접근하려고 하면 `rect1`에서 직접 접근할 수 없으므로 타입 에러가 발생합니다. 이렇게 인스턴스(`rect1`)에서 직접 접근할 수 없는 메서드를 **스태틱 메서드**라고 합니다.

스태틱 메서드는 생성자 함수(`Rectangle`)를 this로 해야만 호출할 수 있습니다.

**Comment by chaehaeun** [comment]
### 프로토타입 메서드
프로토타입 메서드는 프로토타입 체인에 추가되며, 이를 통해 모든 인스턴스에서 이 메서드를 상속받아 사용할 수 있습니다. 예를 들어, `Array` 객체의 `push, pop` 메서드는 모든 배열 인스턴스에서 사용 가능한 프로토타입 메서드입니다.

### 스태틱 메서드
스태틱 메서드들은 인스턴스 데이터에 접근할 수 없고, 클래스(생성자 함수) 또는 클래스에서 파생된 데이터에 대한 작업을 수행합니다.

프로토타입 메서드는 주로 인스턴스의 상태를 관리하거나 인스턴스 간에 공유되어야 할 기능을 제공하는 반면, 스태틱 메서드는 주로 유틸리티 함수나 인스턴스와 독립적인 작업을 수행하는 데 사용됩니다.

**Comment by Stilllee** [comment]
### 스태틱 메서드
클래스 자체에 직접 정의되는 메서드로, 클래스의 인스턴스가 아닌 클래스 이름을 통해 호출됩니다.
```js
class Example {
  static staticMethod() {
    console.log('나는 스태틱 메서드!');
  }
}

Example.staticMethod(); // "나는 스태틱 메서드!" 출력
```

<br>

### 프로토타입 메서드
클래스의 프로토타입 객체에 정의되는 메서드로, 클래스의 인스턴스를 통해 호출되며 모든 인스턴스가 프로토타입 메서드에 접근할 수 있습니다.
```js
class Example {
  constructor(name) {
    this.name = name;
  }

  prototypeMethod() {
    console.log(`저는 ${this.name}입니다.`);
  }
}

const exampleInstance = new Example('woodstock');
exampleInstance.prototypeMethod(); // "저는 woodstock입니다." 출력
```

**Comment by sryung1225** [comment]
스태틱 메서드와 프로토타입 메서드의 주요 차이점은 호출 방식에 있습니다.

**스태틱 메서드**
- 클래스 레벨에서 호출합니다. 스태틱 메서드는 클래스 자체에 바인딩되어 있기 때문에 클래스 정의 이후 인스턴스를 생성하지 않아도 클래스를 통해 호출할 수 있습니다.
- 인스턴스로 해당 메서드에 접근할 수 없습니다. (=인스턴스 프로퍼티 참조 불가능)

**프로토타입 메서드**
- 클래스 정의 이후 클래스의 인스턴스를 통해 호출합니다.
- 인스턴스로 해당 메서드에 접근할 수 있습니다. (=인스턴스 프로퍼티 참조 가능)

**Comment by lulla-by** [comment]
생성자 함수를 `new` 연산자와 함께 호출하면 인스턴스가 생성됩니다. 이때 해당 `생성자 함수`를 `클래스`라고 하면  해당 `클래스`의  `prototype` 객체 내부의 속성들이 인스턴스에 상속됩니다. 이렇게 인스턴스가 프로토타입 체인을 통해 접근가능한 메서드를 프로토타입 메서드라고 합니다.

반면 prototype내부가 아닌 클래스 자체에 부여한 static 메서드는 상속이 되지 않습니다. 예시는 다음의 예시 코드를 사용하여 확인할 수 있습니다.

```js
let Person = function(name){
this.name = name
}

// prototype method
Person.prototype.getName = function(){
return this.name
}

// static method
Person.staticMethod = function(){
return "this is static method"
}

let suzy = new Person("Suzy")

// 프로토타입 메서드는 인스턴스에서 접근 가능
console.log(suzy.getName()) // Suzy

// static method는 클래스 자체에서 접근 가능
Person.staticMethod() // 'this is static method'

// 인스턴스에서 static method는 접근 불가능, 인스턴스에서 접근시 에러 발생
suzy.staticMethod() //  Uncaught TypeError: suzy.staticMethod is not a function
```
