### ISSUE TITLE
7.3.2_클래스가 구체적인 데이터를 지니지 않게 하는 방법(클래스 상속 및 추상화 방법)을 설명해주세요.

### ISSUE THREAD

**Issue by eeeyooon** [Coding-Village-Protector/core-js#32]
📝 (나중에 추가 예정)p
❓ 클래스가 구체적인 데이터를 지니지 않게 하는 방법은 어떤 것들이 있나요? 방법들을 간단하게 설명하고 그 중 하나의 방법을 선택하여 예제 코드를 작성해주세요.

**Comment by lulla-by** [comment]
1. 프로퍼티들을 일일이 지우고 새로운 프로퍼티를 추가할 수 없도록 하는 방법
2. 브릿지(빈함수)를 사용하는 방법
3. Object.create를 사용하는 방법

이중에서 Object.create를 사용하여 SubClass의 prototype의 SuperClass의 prototype을 바라보되, SuperClass의 인스턴스가 되지 않게 만들었습니다

```js

let Animal = function(name, type) {
    this.name = name;
    this.type = type;
}

Animal.prototype.getInfo = function() {
    return this.name + " is " + this.type;
}

let Dog = function(name) {
    Animal.call(this, name, "dog");
}

Dog.prototype = Object.create(Animal.prototype);
Object.freeze(Dog.prototype)


let star = new Dog("Star");

star.getInfo() // "Star is dog"

```
`Dog`라는 `SubClass`의 `prototype`을 `Object.create()`를 사용하여 `Animal`의 프로토타입을 바라보도록 프로토타입 체인을 설정해주었습니다.

이를 통해 `Dog`의 `prototype`은 구체적인 데이터를 지니지 않고 `Animal`을 상속받을 수 있으며 `new Dog()`로 생성된 인스턴스는 `Animal`의 프로토타입 메서드를 사용할 수 있습니다.

**Comment by chaehaeun** [comment]
클래스가 구체적인 데이터를 지니지 않게 하는 방법으로는
- **인스턴스 생성 후 프로퍼티 제거하는 방법** 
  - 인스턴스를 생성한 후 프로퍼티를 일일이 지우고, 더는 새로운 프로퍼티를 추가할 수 없도록 freeze 하는 방법
- **빈 생성자 함수를 만들어 활용하는 방법**
  -  `SubClass`의 prototype에 직접 `SuperClass`의 인스턴스를 할당하는 대신 빈 생성자 함수 `Bridge`를 만들어, 이 함수의 prototype이 `SuperClass`의 prototype을 바라보게 한 다음 `SubClass`의 prototype에는  `Bridge` 함수의 인스턴스를 할당하는 방법.
- **Object.create 를 활용하는 방법** 
  - `Object.create`를 활용하여 `SubClass`의 prototype의 __proto__가 `SuperClass`의 prototype 을 바라보되, SuperClass의 인스턴스가 되지는 않게하는 방법

이 있습니다.

이 중 세 번째 방법의 예제입니다.

```js
var extendClass3 = function (SuperClass, SubClass, subMethods) {
  SubClass.prototype = Object.create(SuperClass.prototype);
  SubClass.prototype.constructor = SubClass;
  if (subMethods) {
    for (var method in subMethods) {
      SubClass.prototype[method] = subMethods[method];
    }
  }
  Object.freeze(SubClass.prototype);
  return SubClass;
};
```

**Comment by Stilllee** [comment]
클래스가 구체적인 데이터를 지니지 않게 하는 방법은 다음과 같습니다.
 
### 1. 인스턴스 생성 후 프로퍼티 제거
클래스의 인스턴스를 생성한 후, 이 인스턴스의 모든 프로퍼티를 삭제하고 새로운 프로퍼티를 추가할 수 없게 하는 방법으로, 객체의 멤버를 직접 조작하기 대문에 번거롭고 위험할 수 있습니다.

### 2. 빈 함수 활용
빈 함수를 사용하여 중간 단계를 만드는 방법입니다. 이 빈 함수의 프로토타입은 상위 클래스의 프로토타입을 참조하고, 하위 클래스의 프로토타입은 이 빈 함수의 인스턴스를 참조합니다. 이 방법은 상위 클래스의 프로토타입 메서드를 상속하면서도, 상위 클래스의 구체적인 데이터는 상속받지 않도록 합니다.

### Object.create 활용
`Object.create()`를 사용하여 하위 클래스의 프로토타입을 생성하는 방법입니다. 이 함수는 주어진 프로토타입을 가진 새로운 객체를 만들기 때문에, 상위 클래스의 인스턴스를 생성하지 않고도 상위 클래스의 프로토타입 메서드를 상속할 수 있습니다.

#### 예제코드
```js
class Animal {
  constructor(name) {
    this.name = name;
  }

  speak() {
    console.log(`${this.name}가 말해요`);
  }
}

class Duck extends Animal {
  constructor(name) {
    super(name);
  }

  // 상속 받은 speak 메서드 오버라이딩
  speak() {
    console.log(`${this.name}는 꽥꽥`);
  }
}

// Duck 클래스의 프로토타입 설정
Duck.prototype = Object.create(Animal.prototype);
Duck.prototype.constructor = Duck; // constructor를 Duck으로 설정

const duck = new Duck('황금오리');
duck.speak(); // 황금오리는 꽥꽥
```

이 코드에서 `Duck`클래스는 `Animal`클래스의 프로토타입 메서드를 상속받지만, `Animal`클래스의 인스턴스가 아닙니다. `Object.create()`를 사용하여 `Duck.prototype`을 `Animal.prototype`의 새로운 인스턴스로 설정하고, `constructor`프로퍼티를 `Duck`으로 다시 설정합니다. 이를 통해 클래스 간의 상속을 깔끔하게 구현할 수 있습니다.

**Comment by Stilllee** [comment]
클래스가 구체적인 데이터를 지니지 않게 하는 방법은 다음과 같습니다.
 
### 1. 인스턴스 생성 후 프로퍼티 제거
클래스의 인스턴스를 생성한 후, 이 인스턴스의 모든 프로퍼티를 삭제하고 새로운 프로퍼티를 추가할 수 없게 하는 방법으로, 객체의 멤버를 직접 조작하기 대문에 번거롭고 위험할 수 있습니다.

### 2. 빈 함수 활용
빈 함수를 사용하여 중간 단계를 만드는 방법입니다. 이 빈 함수의 프로토타입은 상위 클래스의 프로토타입을 참조하고, 하위 클래스의 프로토타입은 이 빈 함수의 인스턴스를 참조합니다. 이 방법은 상위 클래스의 프로토타입 메서드를 상속하면서도, 상위 클래스의 구체적인 데이터는 상속받지 않도록 합니다.

### Object.create 활용
`Object.create()`를 사용하여 하위 클래스의 프로토타입을 생성하는 방법입니다. 이 함수는 주어진 프로토타입을 가진 새로운 객체를 만들기 때문에, 상위 클래스의 인스턴스를 생성하지 않고도 상위 클래스의 프로토타입 메서드를 상속할 수 있습니다.

#### 예제코드
```js
function Animal(name) {
  this.name = name;
}

Animal.prototype.speak = function() {
  console.log(`${this.name}가 말해요`);
};

function Duck() {
}

Duck.prototype = Object.create(Animal.prototype);
Duck.prototype.constructor = Duck;

const duck = new Duck();
duck.speak(); // "undefined가 말해요"
```
이 코드에서 `Duck` 클래스가 `Animal` 클래스의 메서드는 상속받되, 구체적인 데이터 `name`은 상속받지 않습니다.

**Comment by sryung1225** [comment]
### 1. 인스턴스 생성 후 프로퍼티 제거
인스턴스를 일단 생성한 뒤 프로퍼티들을 일일이 지우고, 더는 새로운 프로퍼티를 추가할 수 없도록 하는 것입니다.
프로퍼티가 많은 경우를 대비해 위 동작을 함수로 만들어 사용할 수 있으며, 
제안할 수 있는 방법 중 가장 깔끔하고 간단한 방법입니다.
```jsx
var extendClass1 = function(SuperClass, SubClass, subMethods) {
  SubClass.prototype = new SuperClass();
  for (var prop in SubClass.prototype) { // 생성한 인스턴스를 순환하면서
    if (SubClass.prototype.hasOwnProperty(prop)) { // 프로퍼티 제거
      delete SubClass.prototype[prop];
    }
  }
  if (subMethods) {
    for (var method in subMethods) {
      SubClass.prototype[method] = subMethods[method];
    }
  }
  Object.freeze(SubClass.prototype);
  return SubClass;
};

var Rectangle = function(width, height) {
  this.width = width;
  this.height = height;
};
Rectangle.prototype.getArea = function() {
  return this.width * this.height;
};
var Square = extendClass1(Rectangle, function(width) {
  Rectangle.call(this, width, width);
});
var sq = new Square(5);
console.log(sq.getArea()); // ? 25
```

### 2. 빈 함수 활용
더글라스 크락포드가 제시해 대중적으로 알려진 방법입니다.
`SubClass`의 prototype에 직접 `SuperCalss`의 인스턴스를 할당하는 대신 
아무런 프로퍼티를 생성하지 않는 빈 생성자 함수(`Bridge`)를 하나 더 만들어 그 prototype을 바라보게끔 한 다음
`SubClass`의 prototype에는 `Bridge`의 인스턴스를 할당하게 하는 것입니다.

### 3. `Object.create` 활용
ES5에서 도입된 `Object.create`를 활용하여
`SubClass`의 prototype의 `__proto__`가 `SuperClass`의 prototype을 바라보되 `SuperClass`의 인스턴스가 되지 않게 하는 것입니다.

**Comment by eeeyooon** [comment]
클래스 상속 과정에서 하위 클래스가 상위 클래스의 프로토타입 메서드는 상속 받되, 상위 클래스의 구체적인 데이터는 상속 받지 않도록 하는 방법은 크게 세가지가 있습니다.

1. 인스턴스 생성 후 프로퍼티 제거

`SubClass.prototype`에 `SuperClass`의 인스턴스를 할당한 후, `SubClass.prototype`의 프로퍼티를 모두 삭제하고 `Object.freeze()`를 이용해 더 이상 프로퍼티가 추가되지 않도록 하는 방법입니다.

2. 빈 함수를 다리 역할로 활용

빈 함수를 선언하고, 이 함수의 프로토타입에 `SuperClass.prototype`을 할당한 후, 이 빈 함수의 인스턴스를 `SubClass.prototype`으로 설정합니다. `SuperClass`의 인스턴스를 직접 `Subclass.prototype`에 할당하는 것을 막아 구체적인 데이터의 상속을 방지합니다.

3. `Object.create()` 이용

`Object.create()` 를 이용해 `SuperClass.prototype`을 상속 받는 새로운 객체를 생성하고, 이 객체를 `SubClass.prototype`에 할당합니다. 이 방법이 가장 직관적이며 코드가 간결하여 많이 사용되는 방법 중 하나입니다.

`Object.create()` 예제 코드

```jsx
// 상위 클래스
var SuperClass = function(name) {
    this.name = name;
};

SuperClass.prototype.getName = function() {
    return this.name;
};

// 하위 클래스
var SubClass = function(name, age) {
    SuperClass.call(this, name); // 상위 클래스의 생성자 호출
    this.age = age;
};

// Object.create()를 이용하여 상위 클래스의 프로토타입을 상속
SubClass.prototype = Object.create(SuperClass.prototype);
SubClass.prototype.constructor = SubClass; // constructor가 원래의 Subclass를 바라보도록 복구

// 하위 클래스의 메서드 추가
SubClass.prototype.getAge = function() {
    return this.age;
};

// 인스턴스 생성 및 사용
var instance = new SubClass('Loopy', 7);
console.log(instance.getName()); // Loopy
console.log(instance.getAge()); // 7

```

`Object.create()`를 사용하여 `Subclass.prototype`에 `SuperClass.prototype`을 상속시켜, `SuperClass`의 메서드는 상속받되, `SuperClass`의 인스턴스 프로퍼티는 상속받지 않도록 하였습니다. 추가로, `SubClass.prototype.constructor`가 원래의 `SubClass`를 바라보도록 하였습니다.
