### ISSUE TITLE
7.4_ES6에서 공식적으로 도입된 클래스 문법의 사용 예제를 작성해주세요.

### ISSUE THREAD

**Issue by sryung1225** [Coding-Village-Protector/core-js#34]
📝 p197
❓ 자바스크립트는 프로토타입 기반 객체지향 언어로 클래스가 필요 없는 언어이지만 클래스 기반인 다른 언어에 익숙한 개발자들로부터 니즈가 발생하여 ES6에서 클래스 문법이 공식적으로 추가되었습니다.
ES6 클래스 문법을 사용한 예제를 자유롭게(간단하게) 작성하고 설명해주세요.

**Comment by chaehaeun** [comment]
```js
class Book {
  constructor(title, author, year) {
    this.title = title;    // 책의 제목
    this.author = author;  // 책의 저자
    this.year = year;      // 출판년도
  }

  displayInfo() {
    console.log(`${this.year}년에 출판된 ${this.author}의 "${this.title}"`);
  }
}

const myBook = new Book('1984', '조지오웰', 1949);

myBook.displayInfo();  // 출력: 1949년에 출판된 조지오웰의 "1984"
```
- **클래스 정의** : `class` 키워드를 사용해 `Book` 클래스를 정의합니다. 이 클래스는 책의 제목, 저자, 그리고 출판 년도를 속성으로 가집니다.
- **생성자** : `constructor` 메서드는 새로운 `Book` 객체를 생성하고 초기화할 때 호출됩니다. 이 메서드는 책의 제목, 저자, 출판 년도를 매개변수로 받아 객체의 해당 속성을 설정합니다.
- **메서드** : `displayInfo` 메서드는 책의 정보를 포맷된 문자열로 콘솔에 출력합니다. 이 메서드는 객체의 `title`, `author`, `year` 속성을 활용합니다.
- **인스턴스 생성** : `new` 키워드를 사용하여 `Book` 클래스의 인스턴스를 생성합니다. 생성자에 '1984', 'George Orwell', 1949라는 세 개의 인자를 전달하여 인스턴스를 초기화합니다.
- **메서드 호출** : 생성된 인스턴스 `myBook`에서 `displayInfo` 메서드를 호출하여 책의 상세 정보를 출력합니다.

**Comment by eeeyooon** [comment]
```js
class BaseBall {
    constructor(team, rank) {
        this.team = team;
        this.rank = rank;
    }

    todo() {
        console.log(`2024 시즌에서 ${this.team} 은(는) ${this.rank}위를 한다.`);
    }
}

const LGTWINS = new BaseBall("LG 트윈스", 1);
 
LGTWINS.todo(); // 2024 시즌에서 LG 트윈스 은(는) 1위를 한다.
```

`BaseBall` 클래스는 `constructor` 메서드를 통해 인스턴스 생성 시 초기화 될 `team`과 `rank`를 정의합니다. `todo` 메서드는 인스턴스의 팀과 순위를 가지고 문자열을 콘솔에 출력합니다.

`new` 생성자와 함께 `LGTWINS` 인스턴스를 생성하고, `BaseBall` 클래스의 `constructor`에  "LG 트윈스"와 1을 넘겨줍니다. 
그 후 `LGTWINS`의 `todo` 메서드를 호출하여 2024 시즌 순위 결과를 출력합니다.

**Comment by lulla-by** [comment]
es6에서는 클래스를 좀 더 직관적으로 생성 할 수 있도록 Class문법이 추가되었습니다. 특히 `스태틱메서드`와 `프로토타입메서드`를 위주로 설명하겠습니다.

```js
class Person {
    constructor(name){
        this.name = name;
    }

    static staticMethod (){
        return this.name
    }

    prototypeMethod(){
        return this.name
    }
}

let suzy = new Person("Suzy")

console.log(Person.staticMethod()) // Person
console.log(suzy.prototypeMethod()) // Suzy
```

class 문법 도입 이후로는 `static`이라는 키워드를 사용할 수 있습니다. 

이 `static` 키워드를 사용할 경우 클래스의 인스턴스에서 직접 호출할 수 없고, 클래스 자체에서 호출됩니다. 즉, `스태틱메서드`로 설정됩니다. 

만약 해당 키워드 없이 메서드를 설정하면 클래스의 `prototype`에 메서드가 설정되어 프로토타입 체인으로 접근이 가능한 `프로토타입메서드`로 설정이 됩니다.

**Comment by Stilllee** [comment]
```js
class Pokemon {
  constructor(name, type, color) {
    this.name = name;
    this.type = type;
    this.color = color;
  }
  
  pokemonInfo() {
      console.log(`앗, 야생의 ${this.name}이(가) 나타났다! 색상은 ${this.color}이고, ${this.type}타입 포켓몬이구나!`)
    }
}

const popplio = new Pokemon('누리공', '물', '파랑');

popplio.pokemonInfo();
// 출력 결과 : 앗, 야생의 누리공이(가) 나타났다! 색상은 파랑이고, 물타입 포켓몬이구나!
```
- `Pokemon` 클래스
    - `constructor` 로 객체의 `name`, `type`, `color`속성을 초기화
    - 메서드 `pokemonInfo`는 객체의 정보를 출력
- `popplio` 인스턴스 
    - `new`  키워드로 '누리공', '물', '파랑'이라는 속성 값을 가지는 인스턴스를 생성
    - `popplio`객체의 `pokemonInfo`를 호출해 정보를 출력

**Comment by sryung1225** [comment]
```js
const 소금빵 = class { // 클래스
  constructor(원가, 이율) { // 생성자
    this.원가 = 원가;
    this.이율 = 이율;
  }
  얼마() { // 클래스 인스턴스
    return this.원가 * this.이율;
  }
};
const 초코소금빵 = class extends 소금빵 { // 클래스 상속 적용
  constructor(원가, 이율) {
    super(원가 * 2, 이율);
  }
  얼마() {
    console.log(`손님 ${super.얼마()}원 이에요`);
  }
};

const 짱구네초코소금빵 = new 초코소금빵(1000, 3);
짱구네초코소금빵.얼마(); // ? 손님 6000원 이에요
```
