### ISSUE TITLE
1.5.2_기본형, 참조형 데이터의 복사 과정에서 할당 중에 생기는 차이로 인해 참조형 데이터의 복사 이후 동작에서 발생할 수 있는 문제와 해결 방법을 설명해주세요.

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/core-js#5]
📝 p25 (1-4-3 변수 복사 비교 참고)
❓ 기본형 및 참조형 데이터의 복사는 할당 과정 중에 생기는 차이가 있습니다. 이러한 차이로 기본형 데이터와 참조형 데이터는 복사 과정 이후 동작에서도 큰 차이가 발생하는데요.  만약 참조형 데이터의 복사 이후 복사한 변수의 프로퍼티를 변경할 경우 발생할 수 있는 문제와 해결 방법을 설명해주세요.

**Comment by chaehaeun** [comment]
할당으로 복사한 두 객체는 메모리 상으로 같은 주소값을 참조하고 있기 때문에 복사된 객체의 프로퍼티를 변경할 경우 원본 객체의 프로퍼티도 함께 변경되는 현상이 일어납니다. 
이 문제가 발생하지 않기 위해서는 객체의 얕은 복사 또는 깊은 복사를 통해 별도의 객체를 생성해주어야 됩니다.

**Comment by Stilllee** [comment]
## 어떤 문제가 발생하는가?
복사한 데이터의 프로퍼티를 변경할 경우 원본이 훼손된다.

#### 예제 1.
```js
var user = {
  firstName: "Woodstock",
  lastName: "Lee"
};

var copyUser = function (user, newName) {
  var newUser = user;
  newUser.firstName = newName;
  return newUser;
}

var user2 = copyUser(user, "Esther")

console.log(user.firstName, user.lastName); // Esther Lee
console.log(user2.firstName, user2.lastName); // Esther Lee
```
#### 예제 2.
```js
var user = {
  firstName: "Woodstock",
  lastName: "Lee",
  address: {
    city: "Seoul",
    country: "Korea"
  },
  personalInfo: {
    mbti: "ISTJ"
    bloodType: "B"
  },
};

// 얕은 복사
var user2 = {...user};

// user2의 중첩된 객체를 변경
user2.details.mbti = "ESTJ";

console.log(user.personalInfo.mbti); // ESTJ
console.log(user2.personalInfo.mbti); // ESTJ
```
<br>

## 해결방법
### 1. 새로운 객체를 반환하여 불변성을 보장한다.
원본 객체를 변경하지 않고 새로운 프로퍼티 값을 가진 새 객체를 생성하여 원본 객체를 보호한다.
```js
var user = {
  firstName: "Woodstock",
  lastName: "Lee"
};

var changeFisrtName = function (user, newName) {
  return {
   firstName: newName,
   lastName: user.lastName,
  }
}

var user2 = changeFirstName(user, "Esther")

console.log(user.firstName, user.lastName); // Woodstock Lee
console.log(user2.firstName, user2.lastName); // Esther Lee
```

### 2. 깊은 복사를 한다.
객체의 모든 중첩된 프로퍼티까지 깊게 복사하여, 복사된 객체가 원본 객체와 완전히 독립적이게 만든다.
```js
var deepCopy = function (obj) {
  // obj가 기본형 데이터일 경우 깊은 복사가  필요 없음
  if (typeof obj !== 'object' || obj === null) {
    return obj; // obj를 그대로 반환
  }

  var copy = {};

  for (var key in obj) {
    if (obj.hasOwnProperty(key)) {
      copy[key] = deepCopy(obj[key]);
    }
  }
  return copy;
}

var user2 = deepCopy(user);
user2.details.mbti = "ESTJ";

console.log(user.details.mbti); // ISTJ
console.log(user2.details.mbti); // ESTJ
```

**Comment by Stilllee** [comment]
## 어떤 문제가 발생하는가?
참조형 데이터를 복사할 때, 복사된 데이터는 원본 데이터와 같은 메모리 주소를 참조한다. 

복사된 데이터의 프로퍼티를 변경하면, 그 변경사항이 동일한 메모리 주소를 참조하는 원본 데이터에도 반영되기 때문에 원본 데이터가 변경되거나 훼손될 수 있다.

#### 예제 1.
```js
var user = {
  firstName: "Woodstock",
  lastName: "Lee"
};

var copyUser = function (user, newName) {
  var newUser = user;
  newUser.firstName = newName;
  return newUser;
}

var user2 = copyUser(user, "Esther")

console.log(user.firstName, user.lastName); // Esther Lee
console.log(user2.firstName, user2.lastName); // Esther Lee
```
#### 예제 2.
```js
var user = {
  firstName: "Woodstock",
  lastName: "Lee",
  personalInfo: {
    mbti: "ISTJ",
    bloodType: "B"
  },
};

// 얕은 복사
var user2 = {...user};

// user2의 중첩된 객체를 변경
user2.personalInfo.mbti = "ESTJ";

console.log(user.personalInfo.mbti); // ESTJ
console.log(user2.personalInfo.mbti); // ESTJ
```
<br>

## 해결방법
### 1. 새로운 객체를 반환하여 불변성을 보장한다.
원본 객체를 변경하지 않고 새로운 프로퍼티 값을 가진 새 객체를 생성하여 원본 객체를 보호한다.
```js
var user = {
  firstName: "Woodstock",
  lastName: "Lee"
};

var changeFisrtName = function (user, newName) {
  return {
   firstName: newName,
   lastName: user.lastName,
  }
}

var user2 = changeFirstName(user, "Esther")

console.log(user.firstName, user.lastName); // Woodstock Lee
console.log(user2.firstName, user2.lastName); // Esther Lee
```

### 2. 깊은 복사를 한다.
객체의 모든 중첩된 프로퍼티까지 깊게 복사하여, 복사된 객체가 원본 객체와 완전히 독립적이게 만든다.
```js
var user = {
  firstName: "Woodstock",
  lastName: "Lee",
  personalInfo: {
    mbti: "ISTJ",
    bloodType: "B"
  },
};

var deepCopy = function (obj) {
  // obj가 기본형 데이터일 경우 깊은 복사가  필요 없음
  if (typeof obj !== 'object' || obj === null) {
    return obj; // obj를 그대로 반환
  }

  var copy = {};

  for (var key in obj) {
    if (obj.hasOwnProperty(key)) {
      copy[key] = deepCopy(obj[key]);
    }
  }
  return copy;
}

var user2 = deepCopy(user);
user2.personalInfo.mbti = "ESTJ";

console.log(user.personalInfo.mbti); // ISTJ
console.log(user2.personalInfo.mbti); // ESTJ
```

**Comment by eeeyooon** [comment]
중첩된 객체에서 참조형 데이터가 저장된 프로퍼티를 복사할 때 그 주솟값만 복사가 되면 해당 프로퍼티에 대해 원본과 사본이 모두 동일한 참조형 데이터의 주소를 가리키게 된다. 이렇게 되어버리면 사본을 바꾸면 원본도 바뀌고, 원본을 바꾸면 사본도 바뀌는 문제가 발생할 수 있다. 이러한 문제가 생기지 않게 하기 위해선 참조형 데이터가 있을 때마다 그 내부의 프로퍼티 복사도 재귀적으로 수행하는 깊은 복사를 하는 것을 권장한다. 이 외에도 간단하게 객체를 JSON 문법으로 표현된 문자열로 전환했다가 다시 JSON 객체로 변경하는 방법이 존재한다.

**Comment by sryung1225** [comment]
참조형 데이터의 복사 이후 복사한 변수의 프로퍼티를 변경하면, 
원본과 사본이 모두 동일한 참조형 데이터의 주소를 참고하고 있어 원본 변수의 프로퍼티도 같이 변경되는 문제가 발생한다.
해결 방법으로 깊은 복사 적용이 있다. 내부의 프로퍼티를 직접 복사하는 식으로 깊은 복사를 적용해 위의 얕은 복사가 일으키는 문제를 해결할 수 있다.

**Comment by lulla-by** [comment]
데이터의 복사는 값 그 자체를 복사하는 것이 아닌 그 값을 가지고 있는 주솟값을 복사하기 때문에 자바스크립트의 모든 데이터 타입은 참조형 데이터입니다. 다만, 기본형 데이터의 복사는 주솟값을 복사하는 과정이 한번만 진행되는 반면 참조형은 한 단계를 더 거친다는 차이가 있습니다.

참조형 데이터의 복사는 프로퍼티를 복사할때 그 주솟값만 복사하게 되므로 해당 프로퍼티에 대하여 원본과 복사본 모두 같은 주소를 바라보게 됩니다. 이때 복사본의 프로퍼티를 변경하게 되면 동일한 주소값을 바라보기 때문에 원본이 훼손됩니다.

여기서 등장하는 개념이 얕은 복사와 깊은 복사입니다. **얕은 복사**는 아래 단계의 값만 복사하는 방법이고 **깊은 복사**는 내부의 모든 값들을 하나하나 복사하는 방법입니다.

복사본을 사용하여 완전히 새로운 데이터를 생성하고 싶을 때 참조형에서는 그 내부의 프로퍼티들을 다시 복사하는 과정이 필요합니다. 이 과정에서 가장 유명한 것은 재귀 함수를 사용하여 깊은 복사를 수행하는 방법입니다.

```js
const copyObjectDeep= function (target){
const result = {}

if(typeof target === "object" && target !== null ){

for(const prop in target){
result[prop] = copyObjectDeep(target[prop]);
}
}else{
result = target;
}

return result;
};
```

target 이 객체인 경우에는 내부 프로퍼티를 순회하며 copyObjectDeep함수를 재귀적으로 호출합니다. 객체가 아닌경우에는 target을 그대로 지정하여 이 함수를 사용하여 복사한 사본은 원본과 사본이 서로 완전히 다른 객체를 참조하여 프로퍼티를 변경하는 경우에도 원본과 사본에 훼손이 발생하지 않습니다.

또한 깊은 복사를 매우 간단하게 수행하는 방법으로 JSON을 사용하는 방법이 있습니다.  `JSON.stringify()`을 사용하여 JSON문법으로 표현된 문자열로 전환한 뒤  `JSON.parse()`를 사용하여 다시 JSON 객체로 바꾸는 방법입니다. 단순하면서 잘 동작한다는 큰 장점이 있지만 메서드나 숨겨진 프로퍼티등과 같이 JSON으로 변경할 수 없는 프로퍼티는 모두 무시한다는 단점이 있습니다. 따라서 httprequest를 통해 받은 데이터를 저장한 객체를 복사하거나 순수한 정보만 다룰 때 사용하기를 권장합니다.
