### ISSUE TITLE
1.5.2_spread operator와 깊은 복사 추가 정리

### ISSUE THREAD

**Issue by lulla-by** [Coding-Village-Protector/core-js#6]
📝 p25
❓ 교재에서는 스프레드 오퍼레이터를 사용한 깊은 복사에 대해 다루지 않지만 스터디를 진행하면서 해당 기능을 사용한 깊은 복사에 대한 이야기가 나와서 이슈로 간단하게 정리했습니다.

스프레드 오퍼레이터를 사용하면 간단하게 깊은 복사를 구현할 수 있다고 알고 계신 분들이 많은데 사실 이 방법은 모든 참조형 데이터에 적용할 수 있는 완벽한 깊은 복사가 아닙니다. 

depth가 1단계로 이루어진 참조형 데이터에서는 이 기능을 사용하여 깊은 복사가 가능하지만 depth가 2단계 이상인 데이터는 얕은 복사로 진행이 됩니다. 

예시 코드도 같이 첨부합니다.

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/bf565cac-bfd5-415b-94ef-49157bf58751)

depth가 1단계인 경우에는 복사본의 데이터를 변경해도 데이터가 이미 완전히 다른 주소를 바라보기에 깊은 복사가 진행된 것을 확인할 수 있습니다.

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/1d46d254-1138-4c55-b52e-6332305447be)

반면 위와 같이 depth가 2단계 이상인 객체의 복사본 내부의 참조 데이터의 값을 변경하면 원본도 같이 변경됩니다.

예시에서는 복사본인 `objDeep2`의 `data`라는 프로퍼티에 접근하여 `c` 프로퍼티의 value를 **newThing**으로 변경했습니다. 이후 두 변수를 콘솔로 확인하면 원본인 `objDeep1`의 `data`속 `c`의  value도 **newThing**으로 변경된 것을 확인할 수 있습니다.

**이처럼 스프레드 오퍼레이터를 사용한 깊은 복사는 1단계로 이루어진 객체에서 사용하시길 권장합니다.**

물론 다음과 같이 내부 참조형 데이터를 한번 더 전개하는 로직을 추가해 깊은 복사를 구현하는 방법이 있지만 그 이상의 depth에서 같은 방법을 사용하여 완전히 새로운 데이터를 생성하는 방법은 권하지 않습니다.

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/b3a69001-68dd-41a1-be6c-c937dcf1749b)

**Comment by Stilllee** [comment]
추가 논의에 대한 정리 감사합니다. 덕분에 새로운 사실을 알았습니다👍🏻

**Comment by eeeyooon** [comment]
잘 정리해주셔서 확실히 이해하고 갑니다. 공유해주셔서 감사드려요 🥰

**Comment by sryung1225** [comment]
스터디 당시에 정신이 없어 말씀해주신 내용을 온전히 이해하지 못하고 넘어갔는데 
따로 이렇게 정리해주셔서 도움이 됐어요!! 감사합니다 😊
