### ISSUE TITLE
2.3.1_함수 선언문과 함수 표현식

### ISSUE THREAD

**Issue by Stilllee** [Coding-Village-Protector/core-js#7]
📝 48p
❓ 다음 코드를 보고, 각 함수 호출 시 나타나는 결과와 이유를 설명해보세요. 
```js 
sayHi("아이바오"); 
sayBye("아이바오"); 

function sayHi(name) { 
	console.log(`Hi, ${name}`); 
}; 

const sayBye = function(name) { 
	console.log(`Bye, ${name}`); 
}; 
```

**Comment by lulla-by** [comment]
함수 선언문의 경우 함수 전체를  호이스팅 된다는 특성이 있습니다. 반면 함수표현식은 선언부만 호이스팅이 되기때문에 함수 자체는 작동하지 않습니다.

호이스팅 완료 시점으로 보자면 다음과 같습니다.

```js
//호이스팅을 마친 상태

// 함수 선언문 전체가 호이스팅
var sayHi = function sayHi(name){
  console.log(`Hi, ${name}`); 
}

// 선언부만 호이스팅
const sayBye;
```

따라서 함수 선언문으로 이루어진 sayHi 의 경우에는 호이스팅이 되어 작동되지만 sayBye는 선언부만 호이스팅 된 상황으로 함수가 할당되지 않았으므로 작동되지 않아 다음과 같이 에러를 발생시킵니다.

![image](https://github.com/Coding-Village-Protector/core-js/assets/107671084/dce3c0e1-f67c-43bd-a854-646aa071d231)

**Comment by eeeyooon** [comment]
1. 함수 선언문(`sayHi`)

Javascript 엔진이 코드를 실행하기 전에 함수 선언문을 먼저 읽고, 메모리에 저장합니다. 이를 호이스팅이라고 합니다. 이로 인해 `sayHi` 함수는 코드 내 어디에서든 호출할 수 있습니다. 따라서 `sayHi("아이바오");` 호출은 정상적으로 작동하여 “Hi, 아이바오”를 출력합니다.

2. 함수 표현식(`sayBye`)

함수 표현식은 변수에 함수를 할당하는 형태로, 이 변수의 호이스팅은 발생하지만, 변수의 초기화는 원래 코드 위치에서 실행됩니다. 즉, `sayBye` 변수 선언은 호이스팅되어 코드 상단에 끌어올려지지만, 함수로의 할당은 `sayBye`가 선언된 위치에서 도달했을 때 이루어집니다. 따라서 `sayBye("아이바오");`를  `sayBye` 함수 표현식이 정의되기 전에 호출하면 `sayBye` 는 아직 `undefined` 이고, `undefined` 는 함수가 아니기 때문에 Erorr가 발생하여 함수 호출이 실패합니다.

**Comment by sryung1225** [comment]
(1) `sayHi` 는 함수 선언문을 통해 함수를 새롭게 정의했습니다. 

함수 선언문은 environment의 정보 수집 과정에서 함수가 전체 호이스팅되기 때문에 아래와 같은 모습이 됩니다. 때문에 매개변수 name을 무사히 집어넣어 함수를 사용할 수 있습니다.

```jsx
var sayHi = function sayHi(name) { // 함수 선언문은 전체를 호이스팅
	console.log(`Hi, ${name}`); 
};
sayHi("아이바오");
// Hi, 아이바오 
```

<br />

(2) `sayBye` 는 (익명) 함수 표현식을 통해 함수를 새롭게 정의했습니다.

함수 표현식은 선언부만 호이스팅되는데, 해당 예제에서는 `const` 를 사용했기 때문에 선언은 진행되지만 초기화는 해당 라인에 도달하기 전까지 진행하지 않는 TDZ 구간에 빠집니다. 때문에 참조 에러가 발생합니다.

```jsx
// 🚨 Error : Uncaught ReferenceError: Cannot access 'sayBye' before initialization
```

<br />

+) 만일 `var sayBye` 였다면?

변수 선언부만 호이스팅되어 아래와 같은 모습이 됩니다. `sayBye("아이바오")` 를 실행할 때에는 변수 `sayBye` 에 값이 할당돼 있지 않아 비어있는 대상을 함수로 여긴 것이기 때문에 타입 에러가 발생합니다.

```jsx
var sayBye;
sayBye("아이바오");
sayBye = function(name) { 
	console.log(`Bye, ${name}`); 
}; 
// 🚨 Error : Uncaught TypeError: sayBye is not a function
```

**Comment by chaehaeun** [comment]
1. sayHi("아이바오");
sayHi는 함수 선언식을 사용하여 정의했기 때문에 함수 호이스팅을 통해 코드 실행 전에 전체 함수가 상단으로 끌어올려집니다. 결과적으로 "Hi, 아이바오"가 출력됩니다.
 
 2. sayBye("아이바오"); 
반면 sayBye는 표현식으로 정의하였기 때문에 변수 선언만 호이스팅 되어 레퍼런스 에러가 납니다.

**Comment by Stilllee** [comment]
### `sayHi` 함수
`sayHi` 함수는 함수 선언문을 사용해 정의되었습니다. 

함수 선언문은 실행 컨텍스트가 활성화될 때, 즉 코드가 실행되기 전에 해당 환경의 정보를 수집하는 과정에서 전체가 호이스팅됩니다. 이는 함수 선언문이 코드의 최상단으로 끌어올려지는 것을 의미합니다. 

따라서 `sayHi` 함수는 호출 위치에 관계없이 접근 가능하며, 선언되기 전에 호출해도 정상적으로 실행됩니다.
<br>

### `sayBye` 함수
반면에 `sayBye` 함수는 함수 표현식을 사용하여 정의되었습니다. 

함수 표현식에서는 변수 선언부(`const sayBye`)는 호이스팅되지만, 함수 할당 부분은 호이스팅되지 않습니다. 

따라서 `sayBye` 함수 호출 시점에는 변수 `sayBye`는 존재하지만, 함수로 할당되지 않은 상태이기 때문에 오류가 발생합니다.
<br>

### 함수 선언문과 함수 표현식의 사용   
- 함수 표현식은 코드의 흐름에 따라 함수가 정의되므로, 조건부 함수 정의나 클로저 생성과 같은 상황에서 유용합니다. 
- 반면, 함수 선언문은 코드 구조를 명확하게 하고, 호이스팅으로 인해 어디서든 호출할 수 있는 이점을 제공합니다.

**Comment by Stilllee** [comment]
> (1) `sayHi` 는 함수 선언문을 통해 함수를 새롭게 정의했습니다.
> 
> 함수 선언문은 environment의 정보 수집 과정에서 함수가 전체 호이스팅되기 때문에 아래와 같은 모습이 됩니다. 때문에 매개변수 name을 무사히 집어넣어 함수를 사용할 수 있습니다.
> 
> ```js
> var sayHi = function sayHi(name) { // 함수 선언문은 전체를 호이스팅
> 	console.log(`Hi, ${name}`); 
> };
> sayHi("아이바오");
> // Hi, 아이바오 
> ```
> 
> 
> (2) `sayBye` 는 (익명) 함수 표현식을 통해 함수를 새롭게 정의했습니다.
> 
> 함수 표현식은 선언부만 호이스팅되는데, 해당 예제에서는 `const` 를 사용했기 때문에 선언은 진행되지만 초기화는 해당 라인에 도달하기 전까지 진행하지 않는 TDZ 구간에 빠집니다. 때문에 참조 에러가 발생합니다.
> 
> ```js
> // 🚨 Error : Uncaught ReferenceError: Cannot access 'sayBye' before initialization
> ```
> 
> 
> +) 만일 `var sayBye` 였다면?
> 
> 변수 선언부만 호이스팅되어 아래와 같은 모습이 됩니다. `sayBye("아이바오")` 를 실행할 때에는 변수 `sayBye` 에 값이 할당돼 있지 않아 비어있는 대상을 함수로 여긴 것이기 때문에 타입 에러가 발생합니다.
> 
> ```js
> var sayBye;
> sayBye("아이바오");
> sayBye = function(name) { 
> 	console.log(`Bye, ${name}`); 
> }; 
> // 🚨 Error : Uncaught TypeError: sayBye is not a function
> ```

호이스팅 관점에서 함수 선언문과 함수 표현식의 차이에 관한 문제를 내었는데, 추가적으로 발생하는 타입의 종류까지 짚어주셔서 관련 내용을 정리해봤습니다.

조원분들이 답변해주신것과 같이,
함수 표현식으로 정의된 함수는 변수 선언부만 호이스팅되고 함수 할당부는 호이스팅되지 않기 때문에 그 전에 접근하려고 하면 에러가 발생합니다.
<br>

다만, @sryung1225 님의 답변처럼 
변수를 선언하는 키워드에 따라 발생하는 에러의 종류에는 차이가 있습니다.

#### let, const 키워드
예제에서는 `const`로 선언했기 때문에 호이스팅과정에서 초기화가 이루어지지 않아 TDZ구간에 빠지게 되고, `ReferenceError`가 발생하게 됩니다. 이는 `let`의 경우에도 마찬가지입니다.
<br>

#### var 키워드
그러나 다음과 같이 `sayBye`를 `const`가 아닌 `var`로 선언하면 `ReferenceError`가 아닌 `TypeError`가 발생합니다.
![chrome_6AM8VsJppU](https://github.com/Coding-Village-Protector/core-js/assets/108785772/b8a35000-4628-4b7b-9d98-561864e07ec6)

이는 호이스팅된 변수 `sayBye`가 `undefined`로 초기화되어있고, 함수 할당이 되어있지 않은 상태에서 함수호출을 하려고 했기 때문인데요,

아시다시피 자바스크립트에서 함수 호출은 괄호`()`를 사용합니다. 
변수 뒤에 `()`를 붙이면 해당 변수가 함수를 참조하고 있다고 가정하고 함수 호출을 시도하는 것이죠.
```js
sayBye("아이바오"); 

var sayBye = function(name) { 
	console.log(`Bye, ${name}`); 
}; 
```
따라서 위 코드는 사실상 아래와 같다고 볼 수 있습니다.
```js
undefined(); // TypeError: ... is not a function
```
`undefined`는 함수가 아니므로, `undefined` 값을 가진 변수를 함수처럼 호출하려고 하면 타입 에러가 발생하는 것입니다.

물론 다른 타입의 값도 마찬가지입니다. 
숫자, 문자열, 객체 등이 함수로 호출되려고 하면 동일한 타입 에러가 발생합니다.
![chrome_nNW2QYnkdi](https://github.com/Coding-Village-Protector/core-js/assets/108785772/932df2d1-5fb1-4a88-ad02-e62dd1e5992b)
