### ISSUE TITLE
2.1_활성화된 실행 컨텍스트가 수집하는 정보에 대해 설명해주세요.

### ISSUE THREAD

**Issue by sryung1225** [Coding-Village-Protector/core-js#8]
📝 p39
❓ 콜 스택의 맨 위에 쌓이는 순간, 즉 어떤 실행 컨텍스트가 활성화될 때 (running execution context)
자바스크립트 엔진은 해당 컨텍스트에 관련된 코드들을 실행하는 데 필요한 환경 정보들을 수집하여 실행 컨텍스트 객체에 저장합니다.
그렇다면 **실행 컨텍스트를 구성하는 두 환경(컴포넌트)** 에 대해서, 그리고 **각 환경이 수집하는 정보들**에 대해 설명해주세요.

**Comment by Stilllee** [comment]
자바스크립트의 실행 컨텍스트는 코드가 실행되는 환경을 나타내며, 주로 다음 두 가지의 주요 컴포넌트로 구성됩니다.

### 1. VariableEnvironment
이 환경은 실행 컨텍스트가 생성될 때의 환경을 나타내며, 여기에는 컨텍스트 내에서 선언된 모든 식별자들(변수, 함수, 매개변수 등)의 초기 상태가 저장됩니다.

한 번 설정된 후, 실행 컨텍스트 내에서 일어나는 변경사항은 반영되지 않습니다. 즉, 초기화 시점의 스냅샷을 유지합니다.

### 2. LexicalEnvironment
이 환경은 실행 컨텍스트가 활성화되어 있는 동안의 상태를 나타냅니다.

`VariableEnvironment`와 초기에는 같은 정보를 가지지만, 실행 도중에 발생하는 변경사항(변수 재할당, 새로운 식별자의 추가 등)이 실시간으로 반영됩니다. 

즉, 실행 중인 컨텍스트의 현재 상태를 반영하며, 코드의 실행에 따라 동적으로 변화합니다.
<br>

위의 두 환경 모두 `environmentRecord`와 `outerEnvironmentReference`를 포함합니다.
#### 1. environmentRecord
텍스트 내의 모든 로컬 변수, 함수 선언, 매개변수 등의 식별자 정보를 저장합니다.

#### 2. outerEnvironmentReference
외부 스코프에 대한 참조를 제공하여, 현재 컨텍스트가 외부 스코프의 변수나 함수에 접근할 수 있게 합니다.

**Comment by lulla-by** [comment]
1. VariableEnvironment
현재 컨텍스트 내의 식별자들에 대한 정보 + 외부 환경 정보 선언 시점의 LexicalEnvironment의 스냅샷이며 변경 사항이 저장되지 않습니다.  var 키워드로 선언되는 변수, 함수 선언문으로 생성된 함수가 저장됩니다.

2. LexicalEnvironment
처음에는 VariableEnvironment와 같지만 변경 사항이 실시간으로 반영된다는 차이점이 있습니다. let, const 키워드로 선언되는 변수가 저장됩니다.

실행컨텍스트를 생성할 때 VariableEnvironment에 정보를 담은 뒤 이것을 복사하여 LexicalEnvironment를 생성하며 이후에는 LexicalEnvironment를 주로 활용합니다. 둘은 초기화 과정에는 사실상 완전히 동일하지만 코드 진행에 따라 달라지게 됩니다.

두 환경은 모두 `environmentRecord`와 `outerEnvironmentReference`를 가지고 있는데 VariableEnvironment는 이들을 스냅샷 형태로 가지고 있습니다.

**Comment by eeeyooon** [comment]
**VariableEnvironment** 

VariableEnvironment 컴포넌트는 실행 컨텍스트가 생성될 때의 환경을 나타냅니다. VariableEnvironment에 담기는 내용은 LexicalEnvrionment 와 같지만 최초 실행 시의 스냅샷을 유지한다는 점이 다릅니다. 실행 컨텍스트를 생성할 때 VariableEnvironment에 정보를 먼저 담은 다음, 이를 그대로 복사해서 lex를 만들고, 이후에는 LexicalEnvrionment 를 주로 활용하게 됩니다.
VariableEnvironment와 LexicalEnvrionment의 내부는 environmentRecord와 outerEnvrionmentReference로 구성되어 있습니다. 

→ 현재 컨텍스트 내의 식별자들에 대한 정보와 외부 환경 정보를 담습니다. 선언 시점의 LexicalEnvrionment의 스냅샷으로, 변경사항은 반영되지 않습니다.


**LexicalEnvrionment**

LexicalEnvrionment 컴포넌트도 현재 컨텍스트의 환경 정보를 포함하지만 VariableEnvironment와 달리 코드 실행 도중 발생하는 변경사항도 실시간으로 반영합니다. 

→ 처음에는 VariabaleEnvironment와 같지만 변경 사항이 실시간으로 반영됩니다.

**Comment by chaehaeun** [comment]
### VariableEnvironment
실행 컨텍스트가 생성될 때의 스냅샷을 저장. 실행 컨텍스트를 생성할 때 VariableEnvironment 에 정보를 먼저 담은 다음, 이를 그대로 복사해서 LexicalEnvironment를 만들고, 이후에는 LexicalEnvironment를 주로 사용하게 된다.

### LexicalEnvrionment
VariableEnvironment와 초기에는 같은 정보를 가지지만, 실행 도중에 발생하는 변경 사항이 실시간으로 반영됨.


VariableEnvironment 와 LexicalEnvrionment는 모두 environmentRecord와, outerEnvironmentReference를 가짐.
- environmentRecord:
environmentRecord에는 현재 컨텍스트와 관련된 코드의 식별자 정보들이 저장된다.
- outerEnvironmentReference:
outerEnvironmentReference는 현재 실행 컨텍스트의 외부 LexicalEnvrionment, 즉 상위 스코프를 참조하는 포인터

**Comment by sryung1225** [comment]
실행 컨텍스트는 Variable Environment 컴포넌트와 Lexical Environment 컴포넌트로 구성됩니다.

**Variable Environment**

- 실행 컨텍스트를 생성할 때 정보를 담는 컴포넌트
- 담기는 내용
    - environmentRecord (환경 레코드) : 현재 컨텍스트와 관련된 코드의 식별자들에 대한 정보. 스코프에 포함된 식별자를 등록하고 등록된 식별자에 바인딩된 값을 관리하는 저장소입니다.
    - outerEnvironmentReference (외부 환경에 대한 참조) : 현재 컨텍스트를 생성한 소스코드를 포함하는 상위 코드의 Lexical Environment(호출된 함수가 선언될 당시의 Lexical Environment)를 참조합니다.
- 담기는 내용은 선언 시점의 스냅샷(snapshot)으로 초기 모습을 유지합니다.

**Lexical Environment**

- Variable Environment의 정보를 그대로 복사해 추후 활용하는 컴포넌트
    - 즉, Variable Environment 컴포넌트와 Lexical Environment 컴포넌트는 하나의 동일한 렉시컬 환경을 참조합니다.
- 담기는 내용 : environmentRecord, outerEnvironmentReference
- 초기에 담기는 내용은 Variable Environment와 완전히 동일하지만 이후 코드 진행에 따라 변경될 수 입니다.

![Untitled](https://github.com/Coding-Village-Protector/core-js/assets/26590099/449f9171-0c83-40b3-8b02-93589438e03f)
